In [1]:
import mysql.connector
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from patsy import dmatrices
from sklearn.cross_validation import train_test_split
from sklearn import metrics
from sklearn.cross_validation import cross_val_score
from sklearn.tree import export_graphviz
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

/Users/yaoxuanchen/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [2]:
rds_host='mybike.c0jxuz6r8olg.us-west-2.rds.amazonaws.com'
name='hibike'
pwd='zx123456'
db_name='bike'
port=3306

conn = mysql.connector.connect(host=rds_host,user=name, password=pwd, database=db_name)

df = pd.read_sql("select * from weather", con=conn)
df1 = pd.read_sql("select * from station_1", con=conn)
df.shape

(311, 6)

In [3]:
df1.tail(10)

,last_update,status,bike_stands,available_bike_stands,available_bikes
1085,2018-04-19 19:43:00,OPEN,31,25,6
1086,2018-04-19 19:46:20,OPEN,31,27,4
1087,2018-04-19 19:50:06,OPEN,31,28,3
1088,2018-04-19 19:52:54,OPEN,31,31,0
1089,2018-04-19 19:55:26,OPEN,31,30,1
1090,2018-04-19 19:57:32,OPEN,31,29,2
1091,2018-04-19 20:05:02,OPEN,31,31,0
1092,2018-04-19 20:15:11,OPEN,31,31,0
1093,2018-04-19 20:15:53,OPEN,31,30,1
1094,2018-04-19 20:20:14,OPEN,31,31,0

In [4]:
df['month'] = df['last_update'].dt.month
df['day'] = df['last_update'].dt.day
df['weekday'] = df['last_update'].dt.weekday_name
df['hour'] = df['last_update'].dt.hour
df['minute'] = df['last_update'].dt.minute

df1['month'] = df1['last_update'].dt.month
df1['day'] = df1['last_update'].dt.day
df1['weekday'] = df1['last_update'].dt.weekday_name
df1['hour'] = df1['last_update'].dt.hour
df1['minute'] = df1['last_update'].dt.minute

In [5]:
df1.minute = (df1.minute > 30) *30

In [6]:
df2 = pd.merge(df, df1, left_on=['minute', 'hour', 'weekday', 'month', 'day'], right_on=['minute', 'hour', 'weekday', 'month', 'day'])
df2

,last_update_x,weather_main,humidity,temp,visibility,wind,month,day,weekday,hour,minute,last_update_y,status,bike_stands,available_bike_stands,available_bikes
0,2018-04-13 01:00:00,Drizzle,93,280.15,6000.0,4.1,4,13,Friday,1,0,2018-04-13 01:12:47,OPEN,31,30,1
1,2018-04-13 01:00:00,Drizzle,93,280.15,6000.0,4.1,4,13,Friday,1,0,2018-04-13 01:22:56,OPEN,31,30,1
2,2018-04-13 01:30:00,Drizzle,93,280.15,7000.0,3.1,4,13,Friday,1,30,2018-04-13 01:33:06,OPEN,31,30,1
3,2018-04-13 01:30:00,Drizzle,93,280.15,7000.0,3.1,4,13,Friday,1,30,2018-04-13 01:43:15,OPEN,31,30,1
4,2018-04-13 01:30:00,Drizzle,93,280.15,7000.0,3.1,4,13,Friday,1,30,2018-04-13 01:53:24,OPEN,31,30,1
5,2018-04-13 02:00:00,Drizzle,93,280.15,7000.0,3.6,4,13,Friday,2,0,2018-04-13 02:03:33,OPEN,31,30,1
6,2018-04-13 02:00:00,Drizzle,93,280.15,7000.0,3.6,4,13,Friday,2,0,2018-04-13 02:13:43,OPEN,31,30,1
7,2018-04-13 02:00:00,Drizzle,93,280.15,7000.0,3.6,4,13,Friday,2,0,2018-04-13 02:23:52,OPEN,31,30,1
8,2018-04-13 02:30:00,Drizzle,93,280.15,7000.0,3.6,4,13,Friday,2,30,2018-04-13 02:34:21,OPEN,31,30,1
9,2018-04-13 02:30:00,Drizzle,93,280.15,7000.0,3.6,4,13,Friday,2,30,2018-04-13 02:44:31,OPEN,31,30,1
10,2018-04-13 02:30:00,Drizzle,93,280.15,7000.0,3.6,4,13,Friday,2,30,2018-04-13 02:54:40,OPEN,31,30,1
11,2018-04-13 03:00:00,Drizzle,93,280.15,6000.0,3.1,4,13,Friday,3,0,2018-04-13 03:04:49,OPEN,31,30,1
12,2018-04-13 03:00:00,Drizzle,93,280.15,6000.0,3.1,4,13,Friday,3,0,2018-04-13 03:14:58,OPEN,31,30,1
13,2018-04-13 03:00:00,Drizzle,93,280.15,6000.0,3.1,4,13,Friday,3,0,2018-04-13 03:25:07,OPEN,31,30,1
14,2018-04-13 03:30:00,Drizzle,100,279.72,6000.0,3.1,4,13,Friday,3,30,2018-04-13 03:35:17,OPEN,31,30,1
15,2018-04-13 03:30:00,Drizzle,100,279.72,6000.0,3.1,4,13,Friday,3,30,2018-04-13 03:45:26,OPEN,31,30,1
16,2018-04-13 03:30:00,Drizzle,100,279.72,6000.0,3.1,4,13,Friday,3,30,2018-04-13 03:55:35,OPEN,31,30,1
17,2018-04-13 04:00:00,Drizzle,100,279.66,6000.0,3.1,4,13,Friday,4,0,2018-04-13 04:05:44,OPEN,31,30,1
18,2018-04-13 04:00:00,Drizzle,100,279.66,6000.0,3.1,4,13,Friday,4,0,2018-04-13 04:15:53,OPEN,31,30,1
19,2018-04-13 04:00:00,Drizzle,100,279.66,6000.0,3.1,4,13,Friday,4,0,2018-04-13 04:26:02,OPEN,31,30,1
20,2018-04-13 05:00:00,Drizzle,100,279.77,7000.0,2.6,4,13,Friday,5,0,2018-04-13 05:00:44,OPEN,31,30,1
21,2018-04-13 05:00:00,Drizzle,100,279.77,7000.0,2.6,4,13,Friday,5,0,2018-04-13 05:10:52,OPEN,31,30,1
22,2018-04-13 05:00:00,Drizzle,100,279.77,7000.0,2.6,4,13,Friday,5,0,2018-04-13 05:12:39,OPEN,31,29,2
23,2018-04-13 05:00:00,Drizzle,100,279.77,7000.0,2.6,4,13,Friday,5,0,2018-04-13 05:22:48,OPEN,31,28,3
24,2018-04-13 05:30:00,Drizzle,100,279.71,5000.0,3.1,4,13,Friday,5,30,2018-04-13 05:32:56,OPEN,31,28,3
25,2018-04-13 05:30:00,Drizzle,100,279.71,5000.0,3.1,4,13,Friday,5,30,2018-04-13 05:37:18,OPEN,31,27,4
26,2018-04-13 05:30:00,Drizzle,100,279.71,5000.0,3.1,4,13,Friday,5,30,2018-04-13 05:47:26,OPEN,31,27,4
27,2018-04-13 05:30:00,Drizzle,100,279.71,5000.0,3.1,4,13,Friday,5,30,2018-04-13 05:54:13,OPEN,31,26,5
28,2018-04-13 06:00:00,Drizzle,100,279.77,5000.0,3.6,4,13,Friday,6,0,2018-04-13 06:04:22,OPEN,31,26,5
29,2018-04-13 06:00:00,Drizzle,100,279.77,5000.0,3.6,4,13,Friday,6,0,2018-04-13 06:14:30,OPEN,31,26,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1007,2018-04-19 17:30:00,Clouds,52,291.15,10000.0,2.6,4,19,Thursday,17,30,2018-04-19 17:51:17,OPEN,31,16,15
1008,2018-04-19 17:30:00,Clouds,52,291.15,10000.0,2.6,4,19,Thursday,17,30,2018-04-19 17:54:31,OPEN,31,18,13
1009,2018-04-19 17:30:00,Clouds,52,291.15,10000.0,2.6,4,19,Thursday,17,30,2018-04-19 17:57:28,OPEN,31,18,13
1010,2018-04-19 18:00:00,Clouds,55,290.64,10000.0,2.6,4,19,Thursday,18,0,2018-04-19 18:00:16,OPEN,31,20,11
1011,2018-04-19 18:00:00,Clouds,55,290.64,10000.0,2.6,4,19,Thursday,18,0,2018-04-19 18:03:14,OPEN,31,19,12
1012,2018-04-19 18:00:00,Clouds,55,290.64,10000.0,2.6,4,19,Thursday,18,0,2018-04-19 18:12:38,OPEN,31,17,14
1013,2018-04-19 18:00:00,Clouds,55,290.64,10000.0,2.6,4,19,Thursday,18,0,2018-04-19 18:15:59,OPEN,31,20,11
1014,2018-04-19 18:00:00,Clouds,55,290.64,10000.0,2.6,4,19,Thursday,18,0,2018-04-19 18:22:31,OPEN,31,21,10
1015,2018-04-19 18:00:00,Clouds,55,290.64,10000.0,2.6,4,19,Thursday,18,0,2018-04-19 18:24:25,OPEN,31,22,9
1016,2018-04-19 18:00:00,Clouds,55,290.64,10000.0,2.6,4,19,Thursday,18,0,2018-04-19 18:28:16,OPEN,31,22,9
1017,2018-04-19 18:30:00,Clouds,59,290.15,10000.0,4.6,4,19,Thursday,18,30,2018-04-19 18:32:08,OPEN,31,20,11
1018,2018-04-19 18:30:00,Clouds,59,290.15,10000.0,4.6,4,19,Thursday,18,30,2018-04-19 18:39:54,OPEN,31,21,10
1019,2018-04-19 18:30:00,Clouds,59,290.15,10000.0,4.6,4,19,Thursday,18,30,2018-04-19 18:44:26,OPEN,31,21,10
1020,2018-04-19 18:30:00,Clouds,59,290.15,10000.0,4.6,4,19,Thursday,18,30,2018-04-19 18:45:25,OPEN,31,20,11
1021,2018-04-19 18:30:00,Clouds,59,290.15,10000.0,4.6,4,19,Thursday,18,30,2018-04-19 18:50:12,OPEN,31,19,12
1022,2018-04-19 18:30:00,Clouds,59,290.15,10000.0,4.6,4,19,Thursday,18,30,2018-04-19 18:53:21,OPEN,31,21,10
1023,2018-04-19 18:30:00,Clouds,59,290.15,10000.0,4.6,4,19,Thursday,18,30,2018-04-19 18:56:18,OPEN,31,22,9
1024,2018-04-19 18:30:00,Clouds,59,290.15,10000.0,4.6,4,19,Thursday,18,30,2018-04-19 18:59:20,OPEN,31,24,7
1025,2018-04-19 19:30:00,Clouds,63,288.59,10000.0,3.6,4,19,Thursday,19,30,2018-04-19 19:32:01,OPEN,31,24,7
1026,2018-04-19 19:30:00,Clouds,63,288.59,10000.0,3.6,4,19,Thursday,19,30,2018-04-19 19:39:56,OPEN,31,24,7
1027,2018-04-19 19:30:00,Clouds,63,288.59,10000.0,3.6,4,19,Thursday,19,30,2018-04-19 19:43:00,OPEN,31,25,6
1028,2018-04-19 19:30:00,Clouds,63,288.59,10000.0,3.6,4,19,Thursday,19,30,2018-04-19 19:46:20,OPEN,31,27,4
1029,2018-04-19 19:30:00,Clouds,63,288.59,10000.0,3.6,4,19,Thursday,19,30,2018-04-19 19:50:06,OPEN,31,28,3
1030,2018-04-19 19:30:00,Clouds,63,288.59,10000.0,3.6,4,19,Thursday,19,30,2018-04-19 19:52:54,OPEN,31,31,0
1031,2018-04-19 19:30:00,Clouds,63,288.59,10000.0,3.6,4,19,Thursday,19,30,2018-04-19 19:55:26,OPEN,31,30,1
1032,2018-04-19 19:30:00,Clouds,63,288.59,10000.0,3.6,4,19,Thursday,19,30,2018-04-19 19:57:32,OPEN,31,29,2
1033,2018-04-19 20:00:00,Clouds,67,288.15,10000.0,4.6,4,19,Thursday,20,0,2018-04-19 20:05:02,OPEN,31,31,0
1034,2018-04-19 20:00:00,Clouds,67,288.15,10000.0,4.6,4,19,Thursday,20,0,2018-04-19 20:15:11,OPEN,31,31,0
1035,2018-04-19 20:00:00,Clouds,67,288.15,10000.0,4.6,4,19,Thursday,20,0,2018-04-19 20:15:53,OPEN,31,30,1
1036,2018-04-19 20:00:00,Clouds,67,288.15,10000.0,4.6,4,19,Thursday,20,0,2018-04-19 20:20:14,OPEN,31,31,0

In [7]:
df2 = df2.drop(['last_update_x'] , axis=1)

In [8]:
categorical_columns = df2[['weather_main', 'weekday', 'status']]
for column in categorical_columns:
    df2[column] = df2[column].astype('category')
df2.select_dtypes(['category']).describe().T

             count unique        top  freq
weather_main  1037      6     Clouds   752
weekday       1037      7  Wednesday   280
status        1037      1       OPEN  1037

In [9]:
# Select columns containing continuous data
continuous_columns = []
for column in df2.columns.values:
    if column not in categorical_columns:
        continuous_columns.append(column)
df2['humidity'] = df2['humidity'].astype('float')

continuous_columns.pop(continuous_columns.index('last_update_y'))
print(df2[continuous_columns].dtypes)

humidity                 float64
temp                     float64
visibility               float64
wind                     float64
month                      int64
day                        int64
hour                       int64
minute                     int64
bike_stands                int64
available_bike_stands      int64
available_bikes            int64
dtype: object

In [10]:
df2['minute'] = df2['last_update_y'].dt.minute
df2['minute']
pre_minute = df2['minute'][:-1].tolist()
pre_minute.insert(0, df2['minute'][0])
df2['pre_minute'] = pre_minute
continuous_columns.append('pre_minute')

df2['hour'] = df2['last_update_y'].dt.hour
df2['hour']
pre_hour = df2['hour'][:-1].tolist()
pre_hour.insert(0, df2['hour'][0])
df2['pre_hour'] = pre_hour
continuous_columns.append('pre_hour')
df2

,weather_main,humidity,temp,visibility,wind,month,day,weekday,hour,minute,last_update_y,status,bike_stands,available_bike_stands,available_bikes,pre_minute,pre_hour
0,Drizzle,93.0,280.15,6000.0,4.1,4,13,Friday,1,12,2018-04-13 01:12:47,OPEN,31,30,1,12,1
1,Drizzle,93.0,280.15,6000.0,4.1,4,13,Friday,1,22,2018-04-13 01:22:56,OPEN,31,30,1,12,1
2,Drizzle,93.0,280.15,7000.0,3.1,4,13,Friday,1,33,2018-04-13 01:33:06,OPEN,31,30,1,22,1
3,Drizzle,93.0,280.15,7000.0,3.1,4,13,Friday,1,43,2018-04-13 01:43:15,OPEN,31,30,1,33,1
4,Drizzle,93.0,280.15,7000.0,3.1,4,13,Friday,1,53,2018-04-13 01:53:24,OPEN,31,30,1,43,1
5,Drizzle,93.0,280.15,7000.0,3.6,4,13,Friday,2,3,2018-04-13 02:03:33,OPEN,31,30,1,53,1
6,Drizzle,93.0,280.15,7000.0,3.6,4,13,Friday,2,13,2018-04-13 02:13:43,OPEN,31,30,1,3,2
7,Drizzle,93.0,280.15,7000.0,3.6,4,13,Friday,2,23,2018-04-13 02:23:52,OPEN,31,30,1,13,2
8,Drizzle,93.0,280.15,7000.0,3.6,4,13,Friday,2,34,2018-04-13 02:34:21,OPEN,31,30,1,23,2
9,Drizzle,93.0,280.15,7000.0,3.6,4,13,Friday,2,44,2018-04-13 02:44:31,OPEN,31,30,1,34,2
10,Drizzle,93.0,280.15,7000.0,3.6,4,13,Friday,2,54,2018-04-13 02:54:40,OPEN,31,30,1,44,2
11,Drizzle,93.0,280.15,6000.0,3.1,4,13,Friday,3,4,2018-04-13 03:04:49,OPEN,31,30,1,54,2
12,Drizzle,93.0,280.15,6000.0,3.1,4,13,Friday,3,14,2018-04-13 03:14:58,OPEN,31,30,1,4,3
13,Drizzle,93.0,280.15,6000.0,3.1,4,13,Friday,3,25,2018-04-13 03:25:07,OPEN,31,30,1,14,3
14,Drizzle,100.0,279.72,6000.0,3.1,4,13,Friday,3,35,2018-04-13 03:35:17,OPEN,31,30,1,25,3
15,Drizzle,100.0,279.72,6000.0,3.1,4,13,Friday,3,45,2018-04-13 03:45:26,OPEN,31,30,1,35,3
16,Drizzle,100.0,279.72,6000.0,3.1,4,13,Friday,3,55,2018-04-13 03:55:35,OPEN,31,30,1,45,3
17,Drizzle,100.0,279.66,6000.0,3.1,4,13,Friday,4,5,2018-04-13 04:05:44,OPEN,31,30,1,55,3
18,Drizzle,100.0,279.66,6000.0,3.1,4,13,Friday,4,15,2018-04-13 04:15:53,OPEN,31,30,1,5,4
19,Drizzle,100.0,279.66,6000.0,3.1,4,13,Friday,4,26,2018-04-13 04:26:02,OPEN,31,30,1,15,4
20,Drizzle,100.0,279.77,7000.0,2.6,4,13,Friday,5,0,2018-04-13 05:00:44,OPEN,31,30,1,26,4
21,Drizzle,100.0,279.77,7000.0,2.6,4,13,Friday,5,10,2018-04-13 05:10:52,OPEN,31,30,1,0,5
22,Drizzle,100.0,279.77,7000.0,2.6,4,13,Friday,5,12,2018-04-13 05:12:39,OPEN,31,29,2,10,5
23,Drizzle,100.0,279.77,7000.0,2.6,4,13,Friday,5,22,2018-04-13 05:22:48,OPEN,31,28,3,12,5
24,Drizzle,100.0,279.71,5000.0,3.1,4,13,Friday,5,32,2018-04-13 05:32:56,OPEN,31,28,3,22,5
25,Drizzle,100.0,279.71,5000.0,3.1,4,13,Friday,5,37,2018-04-13 05:37:18,OPEN,31,27,4,32,5
26,Drizzle,100.0,279.71,5000.0,3.1,4,13,Friday,5,47,2018-04-13 05:47:26,OPEN,31,27,4,37,5
27,Drizzle,100.0,279.71,5000.0,3.1,4,13,Friday,5,54,2018-04-13 05:54:13,OPEN,31,26,5,47,5
28,Drizzle,100.0,279.77,5000.0,3.6,4,13,Friday,6,4,2018-04-13 06:04:22,OPEN,31,26,5,54,5
29,Drizzle,100.0,279.77,5000.0,3.6,4,13,Friday,6,14,2018-04-13 06:14:30,OPEN,31,26,5,4,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1007,Clouds,52.0,291.15,10000.0,2.6,4,19,Thursday,17,51,2018-04-19 17:51:17,OPEN,31,16,15,47,17
1008,Clouds,52.0,291.15,10000.0,2.6,4,19,Thursday,17,54,2018-04-19 17:54:31,OPEN,31,18,13,51,17
1009,Clouds,52.0,291.15,10000.0,2.6,4,19,Thursday,17,57,2018-04-19 17:57:28,OPEN,31,18,13,54,17
1010,Clouds,55.0,290.64,10000.0,2.6,4,19,Thursday,18,0,2018-04-19 18:00:16,OPEN,31,20,11,57,17
1011,Clouds,55.0,290.64,10000.0,2.6,4,19,Thursday,18,3,2018-04-19 18:03:14,OPEN,31,19,12,0,18
1012,Clouds,55.0,290.64,10000.0,2.6,4,19,Thursday,18,12,2018-04-19 18:12:38,OPEN,31,17,14,3,18
1013,Clouds,55.0,290.64,10000.0,2.6,4,19,Thursday,18,15,2018-04-19 18:15:59,OPEN,31,20,11,12,18
1014,Clouds,55.0,290.64,10000.0,2.6,4,19,Thursday,18,22,2018-04-19 18:22:31,OPEN,31,21,10,15,18
1015,Clouds,55.0,290.64,10000.0,2.6,4,19,Thursday,18,24,2018-04-19 18:24:25,OPEN,31,22,9,22,18
1016,Clouds,55.0,290.64,10000.0,2.6,4,19,Thursday,18,28,2018-04-19 18:28:16,OPEN,31,22,9,24,18
1017,Clouds,59.0,290.15,10000.0,4.6,4,19,Thursday,18,32,2018-04-19 18:32:08,OPEN,31,20,11,28,18
1018,Clouds,59.0,290.15,10000.0,4.6,4,19,Thursday,18,39,2018-04-19 18:39:54,OPEN,31,21,10,32,18
1019,Clouds,59.0,290.15,10000.0,4.6,4,19,Thursday,18,44,2018-04-19 18:44:26,OPEN,31,21,10,39,18
1020,Clouds,59.0,290.15,10000.0,4.6,4,19,Thursday,18,45,2018-04-19 18:45:25,OPEN,31,20,11,44,18
1021,Clouds,59.0,290.15,10000.0,4.6,4,19,Thursday,18,50,2018-04-19 18:50:12,OPEN,31,19,12,45,18
1022,Clouds,59.0,290.15,10000.0,4.6,4,19,Thursday,18,53,2018-04-19 18:53:21,OPEN,31,21,10,50,18
1023,Clouds,59.0,290.15,10000.0,4.6,4,19,Thursday,18,56,2018-04-19 18:56:18,OPEN,31,22,9,53,18
1024,Clouds,59.0,290.15,10000.0,4.6,4,19,Thursday,18,59,2018-04-19 18:59:20,OPEN,31,24,7,56,18
1025,Clouds,63.0,288.59,10000.0,3.6,4,19,Thursday,19,32,2018-04-19 19:32:01,OPEN,31,24,7,59,18
1026,Clouds,63.0,288.59,10000.0,3.6,4,19,Thursday,19,39,2018-04-19 19:39:56,OPEN,31,24,7,32,19
1027,Clouds,63.0,288.59,10000.0,3.6,4,19,Thursday,19,43,2018-04-19 19:43:00,OPEN,31,25,6,39,19
1028,Clouds,63.0,288.59,10000.0,3.6,4,19,Thursday,19,46,2018-04-19 19:46:20,OPEN,31,27,4,43,19
1029,Clouds,63.0,288.59,10000.0,3.6,4,19,Thursday,19,50,2018-04-19 19:50:06,OPEN,31,28,3,46,19
1030,Clouds,63.0,288.59,10000.0,3.6,4,19,Thursday,19,52,2018-04-19 19:52:54,OPEN,31,31,0,50,19
1031,Clouds,63.0,288.59,10000.0,3.6,4,19,Thursday,19,55,2018-04-19 19:55:26,OPEN,31,30,1,52,19
1032,Clouds,63.0,288.59,10000.0,3.6,4,19,Thursday,19,57,2018-04-19 19:57:32,OPEN,31,29,2,55,19
1033,Clouds,67.0,288.15,10000.0,4.6,4,19,Thursday,20,5,2018-04-19 20:05:02,OPEN,31,31,0,57,19
1034,Clouds,67.0,288.15,10000.0,4.6,4,19,Thursday,20,15,2018-04-19 20:15:11,OPEN,31,31,0,5,20
1035,Clouds,67.0,288.15,10000.0,4.6,4,19,Thursday,20,15,2018-04-19 20:15:53,OPEN,31,30,1,15,20
1036,Clouds,67.0,288.15,10000.0,4.6,4,19,Thursday,20,20,2018-04-19 20:20:14,OPEN,31,31,0,15,20

In [11]:
df2.isnull().sum()

weather_main             0
humidity                 0
temp                     0
visibility               0
wind                     0
month                    0
day                      0
weekday                  0
hour                     0
minute                   0
last_update_y            0
status                   0
bike_stands              0
available_bike_stands    0
available_bikes          0
pre_minute               0
pre_hour                 0
dtype: int64

In [12]:
# Check for irregular cardinality in categorical features. There could be same values spelled differently
for column in categorical_columns:
    print("Unique values for " + column + ":", pd.unique(df2[column].ravel()))

Unique values for weather_main: ['Drizzle' 'Mist' 'Clouds' 'Fog' 'Clear' 'Rain']
Unique values for weekday: ['Friday' 'Saturday' 'Sunday' 'Monday' 'Tuesday' 'Wednesday' 'Thursday']
Unique values for status: ['OPEN']

In [13]:
#df2['pre_available_bikes'][0] = df2['available_bikes'][0]
#df2['pre_available_bikes'].iloc[1:] = df2['available_bikes'][:-1]
#pd.concat([df2['available_bikes'][0:1], df2['available_bikes'][:-1]])
pre_available_bikes = df2['available_bikes'][:-1].tolist()
pre_available_bikes.insert(0, df2['available_bikes'][0])
df2['pre_available_bikes'] = pre_available_bikes
continuous_columns.append('pre_available_bikes')

In [14]:
df_dummies_weather_main = pd.get_dummies(df2[['weather_main']])
print(df_dummies_weather_main.head())
df_dummies_weekday = pd.get_dummies(df2[['weekday']])
df_dummies_weekday.head()

   weather_main_Clear  weather_main_Clouds  weather_main_Drizzle  \
0                   0                    0                     1
1                   0                    0                     1
2                   0                    0                     1
3                   0                    0                     1
4                   0                    0                     1

   weather_main_Fog  weather_main_Mist  weather_main_Rain
0                 0                  0                  0
1                 0                  0                  0
2                 0                  0                  0
3                 0                  0                  0
4                 0                  0                  0

,weekday_Friday,weekday_Monday,weekday_Saturday,weekday_Sunday,weekday_Thursday,weekday_Tuesday,weekday_Wednesday
0,1,0,0,0,0,0,0
1,1,0,0,0,0,0,0
2,1,0,0,0,0,0,0
3,1,0,0,0,0,0,0
4,1,0,0,0,0,0,0

In [15]:
describe_columns = [x for x in continuous_columns if x not in ['available_bike_stands', 'bike_stands', 'available_bikes', 'visibility']]

In [16]:
X = pd.concat([df2[describe_columns], df_dummies_weather_main, df_dummies_weekday], axis =1)
y = df2.available_bikes
X

,humidity,temp,wind,month,day,hour,minute,pre_minute,pre_hour,pre_available_bikes,...,weather_main_Fog,weather_main_Mist,weather_main_Rain,weekday_Friday,weekday_Monday,weekday_Saturday,weekday_Sunday,weekday_Thursday,weekday_Tuesday,weekday_Wednesday
0,93.0,280.15,4.1,4,13,1,12,12,1,1,...,0,0,0,1,0,0,0,0,0,0
1,93.0,280.15,4.1,4,13,1,22,12,1,1,...,0,0,0,1,0,0,0,0,0,0
2,93.0,280.15,3.1,4,13,1,33,22,1,1,...,0,0,0,1,0,0,0,0,0,0
3,93.0,280.15,3.1,4,13,1,43,33,1,1,...,0,0,0,1,0,0,0,0,0,0
4,93.0,280.15,3.1,4,13,1,53,43,1,1,...,0,0,0,1,0,0,0,0,0,0
5,93.0,280.15,3.6,4,13,2,3,53,1,1,...,0,0,0,1,0,0,0,0,0,0
6,93.0,280.15,3.6,4,13,2,13,3,2,1,...,0,0,0,1,0,0,0,0,0,0
7,93.0,280.15,3.6,4,13,2,23,13,2,1,...,0,0,0,1,0,0,0,0,0,0
8,93.0,280.15,3.6,4,13,2,34,23,2,1,...,0,0,0,1,0,0,0,0,0,0
9,93.0,280.15,3.6,4,13,2,44,34,2,1,...,0,0,0,1,0,0,0,0,0,0
10,93.0,280.15,3.6,4,13,2,54,44,2,1,...,0,0,0,1,0,0,0,0,0,0
11,93.0,280.15,3.1,4,13,3,4,54,2,1,...,0,0,0,1,0,0,0,0,0,0
12,93.0,280.15,3.1,4,13,3,14,4,3,1,...,0,0,0,1,0,0,0,0,0,0
13,93.0,280.15,3.1,4,13,3,25,14,3,1,...,0,0,0,1,0,0,0,0,0,0
14,100.0,279.72,3.1,4,13,3,35,25,3,1,...,0,0,0,1,0,0,0,0,0,0
15,100.0,279.72,3.1,4,13,3,45,35,3,1,...,0,0,0,1,0,0,0,0,0,0
16,100.0,279.72,3.1,4,13,3,55,45,3,1,...,0,0,0,1,0,0,0,0,0,0
17,100.0,279.66,3.1,4,13,4,5,55,3,1,...,0,0,0,1,0,0,0,0,0,0
18,100.0,279.66,3.1,4,13,4,15,5,4,1,...,0,0,0,1,0,0,0,0,0,0
19,100.0,279.66,3.1,4,13,4,26,15,4,1,...,0,0,0,1,0,0,0,0,0,0
20,100.0,279.77,2.6,4,13,5,0,26,4,1,...,0,0,0,1,0,0,0,0,0,0
21,100.0,279.77,2.6,4,13,5,10,0,5,1,...,0,0,0,1,0,0,0,0,0,0
22,100.0,279.77,2.6,4,13,5,12,10,5,1,...,0,0,0,1,0,0,0,0,0,0
23,100.0,279.77,2.6,4,13,5,22,12,5,2,...,0,0,0,1,0,0,0,0,0,0
24,100.0,279.71,3.1,4,13,5,32,22,5,3,...,0,0,0,1,0,0,0,0,0,0
25,100.0,279.71,3.1,4,13,5,37,32,5,3,...,0,0,0,1,0,0,0,0,0,0
26,100.0,279.71,3.1,4,13,5,47,37,5,4,...,0,0,0,1,0,0,0,0,0,0
27,100.0,279.71,3.1,4,13,5,54,47,5,4,...,0,0,0,1,0,0,0,0,0,0
28,100.0,279.77,3.6,4,13,6,4,54,5,5,...,0,0,0,1,0,0,0,0,0,0
29,100.0,279.77,3.6,4,13,6,14,4,6,5,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1007,52.0,291.15,2.6,4,19,17,51,47,17,15,...,0,0,0,0,0,0,0,1,0,0
1008,52.0,291.15,2.6,4,19,17,54,51,17,15,...,0,0,0,0,0,0,0,1,0,0
1009,52.0,291.15,2.6,4,19,17,57,54,17,13,...,0,0,0,0,0,0,0,1,0,0
1010,55.0,290.64,2.6,4,19,18,0,57,17,13,...,0,0,0,0,0,0,0,1,0,0
1011,55.0,290.64,2.6,4,19,18,3,0,18,11,...,0,0,0,0,0,0,0,1,0,0
1012,55.0,290.64,2.6,4,19,18,12,3,18,12,...,0,0,0,0,0,0,0,1,0,0
1013,55.0,290.64,2.6,4,19,18,15,12,18,14,...,0,0,0,0,0,0,0,1,0,0
1014,55.0,290.64,2.6,4,19,18,22,15,18,11,...,0,0,0,0,0,0,0,1,0,0
1015,55.0,290.64,2.6,4,19,18,24,22,18,10,...,0,0,0,0,0,0,0,1,0,0
1016,55.0,290.64,2.6,4,19,18,28,24,18,9,...,0,0,0,0,0,0,0,1,0,0
1017,59.0,290.15,4.6,4,19,18,32,28,18,9,...,0,0,0,0,0,0,0,1,0,0
1018,59.0,290.15,4.6,4,19,18,39,32,18,11,...,0,0,0,0,0,0,0,1,0,0
1019,59.0,290.15,4.6,4,19,18,44,39,18,10,...,0,0,0,0,0,0,0,1,0,0
1020,59.0,290.15,4.6,4,19,18,45,44,18,10,...,0,0,0,0,0,0,0,1,0,0
1021,59.0,290.15,4.6,4,19,18,50,45,18,11,...,0,0,0,0,0,0,0,1,0,0
1022,59.0,290.15,4.6,4,19,18,53,50,18,12,...,0,0,0,0,0,0,0,1,0,0
1023,59.0,290.15,4.6,4,19,18,56,53,18,10,...,0,0,0,0,0,0,0,1,0,0
1024,59.0,290.15,4.6,4,19,18,59,56,18,9,...,0,0,0,0,0,0,0,1,0,0
1025,63.0,288.59,3.6,4,19,19,32,59,18,7,...,0,0,0,0,0,0,0,1,0,0
1026,63.0,288.59,3.6,4,19,19,39,32,19,7,...,0,0,0,0,0,0,0,1,0,0
1027,63.0,288.59,3.6,4,19,19,43,39,19,7,...,0,0,0,0,0,0,0,1,0,0
1028,63.0,288.59,3.6,4,19,19,46,43,19,6,...,0,0,0,0,0,0,0,1,0,0
1029,63.0,288.59,3.6,4,19,19,50,46,19,4,...,0,0,0,0,0,0,0,1,0,0
1030,63.0,288.59,3.6,4,19,19,52,50,19,3,...,0,0,0,0,0,0,0,1,0,0
1031,63.0,288.59,3.6,4,19,19,55,52,19,0,...,0,0,0,0,0,0,0,1,0,0
1032,63.0,288.59,3.6,4,19,19,57,55,19,1,...,0,0,0,0,0,0,0,1,0,0
1033,67.0,288.15,4.6,4,19,20,5,57,19,2,...,0,0,0,0,0,0,0,1,0,0
1034,67.0,288.15,4.6,4,19,20,15,5,20,0,...,0,0,0,0,0,0,0,1,0,0
1035,67.0,288.15,4.6,4,19,20,15,15,20,0,...,0,0,0,0,0,0,0,1,0,0
1036,67.0,288.15,4.6,4,19,20,20,15,20,1,...,0,0,0,0,0,0,0,1,0,0

In [17]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from matplotlib.backends.backend_pdf import PdfPages
%matplotlib inline
print(continuous_columns)

['humidity', 'temp', 'visibility', 'wind', 'month', 'day', 'hour', 'minute', 'bike_stands', 'available_bike_stands', 'available_bikes', 'pre_minute', 'pre_hour', 'pre_available_bikes']

# Calculate correlation of all pairs of continuous features
corr = df2[continuous_columns].corr()

# Generate a mask for the upper triangle
mask = np.zeros_like(corr, dtype=np.bool)
mask[np.triu_indices_from(mask)] = True

# Set up the matplotlib figure
f, ax = plt.subplots(figsize=(20, 15))

# Generate a custom colormap
cmap = sns.diverging_palette(220, 10, as_cmap=True)

# Draw the heatmap with the mask and correct aspect ratio
sns.heatmap(corr, annot=True, mask=mask, cmap=cmap, vmax=1, vmin=-1,
            square=True, xticklabels=True, yticklabels=True,
            linewidths=.5, cbar_kws={"shrink": .5}, ax=ax)
plt.yticks(rotation = 0)
plt.xticks(rotation = 45)

In [18]:
#high temp  high wind , hour

In [19]:
#dtc = DecisionTreeClassifier(max_depth=10, random_state=1)
#dtc.fit(X, y)
#print(dtc)

In [20]:
#from sklearn.cross_validation import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=7)

In [21]:
#type(dtc)

In [22]:
# Compute the importance of each feature based on the trained decision tree classifier
#pd.DataFrame({'feature': X.columns, 'importance': dtc.feature_importances_})

import operator

import operator

def tree_print(clf, X):
    """
    Print the tree of a sklearn DecisionTreeClassifier

    Parameters
    ----------
    clf : DecisionTreeClassifier - A tree that has already been fit.
    X : The original training set
    """
    tlevel = _tree_rprint('', clf, X.columns, clf.classes_)
    print('<',end='')
    for i in range(3*tlevel - 2):
        print('-',end='')
    print('>')
    print('Tree Depth: ',tlevel)

def _tree_rprint(kword, clf, features, labels, node_index=0, tlevel_index=0):
    # Note: The DecisionTreeClassifier uses the Tree structure defined in:
    # 		github.com/scikit-learn/scikit-learn/blob/master/sklearn/tree/_tree.pyx
    #       it is an array based tree implementation:

    # indent the nodes according to their tree level
    for i in range(tlevel_index):
        print('  |',end='')

	#  TODO: the following should use the TREE_LEAF constant defined in _tree.pyx
	#        instead of -1, not quite sure how to get at it from the tree user level
    if clf.tree_.children_left[node_index] == -1:  # indicates leaf
        print(kword, end=' ' if kword else '')
        # get the majority label
        count_list = clf.tree_.value[node_index, 0]
        max_index, max_value = max(enumerate(count_list), key=operator.itemgetter(1))
        max_label = labels[max_index]
        print(max_label)
        return tlevel_index
    
    else:
        # compute and print node label
        feature = features[clf.tree_.feature[node_index]]
        threshold = clf.tree_.threshold[node_index]
        print(kword, end=' ' if kword else '')
        print('if {} =< {}: '.format(feature, threshold))
        # recurse down the children
        left_index = clf.tree_.children_left[node_index]
        right_index = clf.tree_.children_right[node_index]
        ltlevel_index = _tree_rprint('then', clf, features, labels, left_index, tlevel_index+1)
        rtlevel_index = _tree_rprint('else', clf, features, labels, right_index, tlevel_index+1)
        # return the maximum depth of either one of the children
        return max(ltlevel_index,rtlevel_index)
tree_print(dtc, X)

X_new = X.loc[300:310]

print(dtc.predict(X_new))
df2.loc[300:310].available_bikes

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

print("Training data:\n", pd.concat([X_train, y_train], axis=1))
print("\nTest data:\n", pd.concat([X_test, y_test], axis=1))

Training data:
       humidity    temp  wind  month  day  hour  minute  pre_minute  pre_hour  \
757       59.0  290.72   9.3      4   18    18      38          32        18
311       93.0  281.66   4.6      4   14    23       3          53        22
366       93.0  281.72  10.8      4   15     8      33          29         8
946       55.0  289.64   9.3      4   19    13      32          27        13
46       100.0  279.15   4.1      4   13     8      12           9         8
884       93.0  285.16   4.6      4   19     8      22          20         8
944       63.0  289.15   8.2      4   19    13      23          20        13
644       87.0  287.18   7.7      4   18    11      48          39        11
382       93.0  282.66  10.3      4   15    11       7          59        10
159      100.0  281.16   3.1      4   13    23      30          18        23
411       93.0  283.16   9.3      4   15    15       5           4        15
5         93.0  280.15   3.6      4   13     2       3          53         1
502       66.0  286.15  11.8      4   17    19      37          37        19
579       93.0  284.16   3.1      4   18     6       8          58         5
508       66.0  285.64  11.3      4   17    20       1          54        19
191       93.0  279.82   2.6      4   14     5      36          26         5
576       93.0  284.30   3.1      4   18     5      50          45         5
427       93.0  284.67   9.3      4   15    17      14           9        17
224       87.0  283.72   6.2      4   14    10      52          47        10
188       93.0  279.39   3.1      4   14     5      10           0         5
60       100.0  279.66   3.1      4   13     9      45          36         9
7         93.0  280.15   3.6      4   13     2      23          13         2
735       76.0  289.99   8.7      4   18    17      18          15        17
458       87.0  283.15   3.6      4   15    21      41          31        21
600       82.0  285.52   8.2      4   18     8       9           4         8
896       82.0  286.66   5.1      4   19     9      14           4         9
495       93.0  282.15   6.7      4   16     3      26          15         3
257       81.0  284.66   7.2      4   14    15      16           9        15
121       93.0  282.26   3.1      4   13    18      51          39        18
907       72.0  287.64   4.6      4   19    10       8          57         9
...        ...     ...   ...    ...  ...   ...     ...         ...       ...
587       93.0  284.72   3.1      4   18     6      57          49         6
295       87.0  283.16   5.1      4   14    21       3          57        20
940       63.0  289.15   8.2      4   19    13      13          10        13
45       100.0  279.15   4.1      4   13     8       9           4         8
800       71.0  286.64   8.7      4   18    22      14           4        22
744       72.0  290.46   8.7      4   18    17      55          52        17
650       87.0  288.18   8.7      4   18    12      20          14        12
70        93.0  280.15   2.6      4   13    10      49          47        10
209       93.0  282.72   4.6      4   14     8      48          41         8
846       93.0  282.87   1.5      4   19     4      49          39         4
534       81.0  284.15   5.1      4   17    23      46          36        23
988       52.0  291.15   4.1      4   19    16      42          31        16
243       81.0  285.29   7.7      4   14    13      40          32        13
78        87.0  281.66   1.5      4   13    12      45          35        12
969       55.0  290.66   6.2      4   19    15      23          12        15
381      100.0  281.73   9.3      4   15    10      59          49        10
630       76.0  287.15   5.7      4   18    10      25          15        10
1022      59.0  290.15   4.6      4   19    18      53          50        18
525       71.0  284.64   6.2      4   17    22      23          12        22
808       71.0  286.64   7.7      4   18    23       5          55        22
461       87.0  283.15   3.1      4   15    22      13           3        22
76        87.0  281.66   1.5      4   13    12      32          18        12
968       55.0  290.66   6.2      4   19    15      12           2        15
876       93.0  284.72   4.6      4   19     7      56          52         7
469       81.0  283.15   5.1      4   15    23      22          12        23
255       81.0  284.66   7.2      4   14    15       3          56        14
831       87.0  284.15   1.5      4   19     2      31          23         2
621       71.0  286.64   6.7      4   18     9      33          27         9
91        87.0  281.66   1.5      4   13    14      56          48        14
147      100.0  280.72   2.6      4   13    21      58          46        21

      pre_available_bikes       ...         weather_main_Mist  \
757                    10       ...                         0
311                    27       ...                         0
366                    28       ...                         0
946                    19       ...                         0
46                     13       ...                         0
884                    20       ...                         0
944                    17       ...                         0
644                    30       ...                         0
382                    31       ...                         0
159                    15       ...                         0
411                    11       ...                         0
5                       1       ...                         0
502                     7       ...                         0
579                     6       ...                         0
508                     4       ...                         0
191                    11       ...                         0
576                     3       ...                         0
427                     6       ...                         0
224                    28       ...                         0
188                    10       ...                         0
60                     30       ...                         0
7                       1       ...                         0
735                    19       ...                         0
458                     5       ...                         0
600                     6       ...                         0
896                    23       ...                         0
495                     0       ...                         0
257                    30       ...                         0
121                     6       ...                         1
907                    31       ...                         0
...                   ...       ...                       ...
587                    10       ...                         0
295                    21       ...                         0
940                    31       ...                         0
45                     12       ...                         0
800                    12       ...                         0
744                    12       ...                         0
650                    31       ...                         0
70                     31       ...                         0
209                    27       ...                         0
846                     0       ...                         0
534                     0       ...                         0
988                    14       ...                         0
243                    28       ...                         0
78                     31       ...                         0
969                    10       ...                         0
381                    31       ...                         0
630                    26       ...                         0
1022                   12       ...                         0
525                     2       ...                         0
808                     6       ...                         0
461                     4       ...                         0
76                     31       ...                         0
968                    10       ...                         0
876                    17       ...                         0
469                     2       ...                         0
255                    31       ...                         0
831                     0       ...                         0
621                    17       ...                         0
91                     27       ...                         0
147                    19       ...                         0

      weather_main_Rain  weekday_Friday  weekday_Monday  weekday_Saturday  \
757                   0               0               0                 0
311                   0               0               0                 1
366                   0               0               0                 0
946                   0               0               0                 0
46                    0               1               0                 0
884                   0               0               0                 0
944                   0               0               0                 0
644                   0               0               0                 0
382                   0               0               0                 0
159                   0               1               0                 0
411                   1               0               0                 0
5                     0               1               0                 0
502                   0               0               0                 0
579                   0               0               0                 0
508                   0               0               0                 0
191                   0               0               0                 1
576                   0               0               0                 0
427                   0               0               0                 0
224                   1               0               0                 1
188                   0               0               0                 1
60                    0               1               0                 0
7                     0               1               0                 0
735                   0               0               0                 0
458                   1               0               0                 0
600                   0               0               0                 0
896                   0               0               0                 0
495                   1               0               1                 0
257                   0               0               0                 1
121                   0               1               0                 0
907                   0               0               0                 0
...                 ...             ...             ...               ...
587                   0               0               0                 0
295                   0               0               0                 1
940                   0               0               0                 0
45                    0               1               0                 0
800                   0               0               0                 0
744                   0               0               0                 0
650                   0               0               0                 0
70                    0               1               0                 0
209                   0               0               0                 1
846                   0               0               0                 0
534                   0               0               0                 0
988                   0               0               0                 0
243                   0               0               0                 1
78                    0               1               0                 0
969                   0               0               0                 0
381                   0               0               0                 0
630                   0               0               0                 0
1022                  0               0               0                 0
525                   0               0               0                 0
808                   0               0               0                 0
461                   0               0               0                 0
76                    0               1               0                 0
968                   0               0               0                 0
876                   0               0               0                 0
469                   0               0               0                 0
255                   0               0               0                 1
831                   0               0               0                 0
621                   0               0               0                 0
91                    0               1               0                 0
147                   0               1               0                 0

      weekday_Sunday  weekday_Thursday  weekday_Tuesday  weekday_Wednesday  \
757                0                 0                0                  1
311                0                 0                0                  0
366                1                 0                0                  0
946                0                 1                0                  0
46                 0                 0                0                  0
884                0                 1                0                  0
944                0                 1                0                  0
644                0                 0                0                  1
382                1                 0                0                  0
159                0                 0                0                  0
411                1                 0                0                  0
5                  0                 0                0                  0
502                0                 0                1                  0
579                0                 0                0                  1
508                0                 0                1                  0
191                0                 0                0                  0
576                0                 0                0                  1
427                1                 0                0                  0
224                0                 0                0                  0
188                0                 0                0                  0
60                 0                 0                0                  0
7                  0                 0                0                  0
735                0                 0                0                  1
458                1                 0                0                  0
600                0                 0                0                  1
896                0                 1                0                  0
495                0                 0                0                  0
257                0                 0                0                  0
121                0                 0                0                  0
907                0                 1                0                  0
...              ...               ...              ...                ...
587                0                 0                0                  1
295                0                 0                0                  0
940                0                 1                0                  0
45                 0                 0                0                  0
800                0                 0                0                  1
744                0                 0                0                  1
650                0                 0                0                  1
70                 0                 0                0                  0
209                0                 0                0                  0
846                0                 1                0                  0
534                0                 0                1                  0
988                0                 1                0                  0
243                0                 0                0                  0
78                 0                 0                0                  0
969                0                 1                0                  0
381                1                 0                0                  0
630                0                 0                0                  1
1022               0                 1                0                  0
525                0                 0                1                  0
808                0                 0                0                  1
461                1                 0                0                  0
76                 0                 0                0                  0
968                0                 1                0                  0
876                0                 1                0                  0
469                1                 0                0                  0
255                0                 0                0                  0
831                0                 1                0                  0
621                0                 0                0                  1
91                 0                 0                0                  0
147                0                 0                0                  0

      available_bikes
757                12
311                26
366                29
946                20
46                 14
884                21
944                18
644                31
382                31
159                11
411                11
5                   1
502                 7
579                 6
508                 2
191                11
576                 4
427                 6
224                27
188                10
60                 27
7                   1
735                18
458                 5
600                 7
896                24
495                 0
257                31
121                10
907                30
...               ...
587                11
295                20
940                30
45                 13
800                13
744                11
650                31
70                 30
209                30
846                 0
534                 0
988                13
243                29
78                 31
969                10
381                31
630                26
1022               10
525                 2
808                 5
461                 3
76                 31
968                10
876                19
469                 2
255                30
831                 0
621                18
91                 24
147                18

[725 rows x 24 columns]

Test data:
       humidity    temp  wind  month  day  hour  minute  pre_minute  pre_hour  \
782       59.0  289.15   6.7      4   18    20      32          21        20
330      100.0  281.66   5.1      4   15     2       3          53         1
730       76.0  289.99   8.7      4   18    17       5           2        17
278       76.0  284.77   7.7      4   14    18      22           8        18
208       93.0  282.72   4.6      4   14     8      41          29         8
985       55.0  290.64   5.7      4   19    16      24          18        16
19       100.0  279.66   3.1      4   13     4      26          15         4
733       76.0  289.99   8.7      4   18    17      12          10        17

# Refit the model on the training set only
dtc.fit(X_train, y_train)

# Predict on the hold-out test set
predictions_test = dtc.predict(X_test)
df_true_vs_predicted_test = pd.DataFrame({'ActualClass': y_test, 'PredictedClass': predictions_test})

df_true_vs_predicted_test

print("Accuracy: ", metrics.accuracy_score(y_test, predictions_test))
print("Confusion matrix: \n", metrics.confusion_matrix(y_test, predictions_test))
print("Classification report:\n ", metrics.classification_report(y_test, predictions_test))

In [24]:
# Train RF with 100 trees
rfc = RandomForestClassifier(n_estimators=100, max_features='auto', oob_score=True, random_state=1)
rfc.fit(X, y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=True, random_state=1, verbose=0, warm_start=False)

In [25]:
pd.DataFrame({'feature': X.columns, 'importance':rfc.feature_importances_})

                 feature  importance
0               humidity    0.041734
1                   temp    0.076558
2                   wind    0.062001
3                  month    0.000000
4                    day    0.030142
5                   hour    0.089855
6                 minute    0.150423
7             pre_minute    0.152988
8               pre_hour    0.090972
9    pre_available_bikes    0.224509
10    weather_main_Clear    0.006035
11   weather_main_Clouds    0.008314
12  weather_main_Drizzle    0.008061
13      weather_main_Fog    0.001244
14     weather_main_Mist    0.001454
15     weather_main_Rain    0.004731
16        weekday_Friday    0.007623
17        weekday_Monday    0.002601
18      weekday_Saturday    0.011087
19        weekday_Sunday    0.011931
20      weekday_Thursday    0.005926
21       weekday_Tuesday    0.004147
22     weekday_Wednesday    0.007665

In [26]:
rfc.predict_proba(X)
print(X.loc[1])

humidity                 93.00
temp                    280.15
wind                      4.10
month                     4.00
day                      13.00
hour                      1.00
minute                   22.00
pre_minute               12.00
pre_hour                  1.00
pre_available_bikes       1.00
weather_main_Clear        0.00
weather_main_Clouds       0.00
weather_main_Drizzle      1.00
weather_main_Fog          0.00
weather_main_Mist         0.00
weather_main_Rain         0.00
weekday_Friday            1.00
weekday_Monday            0.00
weekday_Saturday          0.00
weekday_Sunday            0.00
weekday_Thursday          0.00
weekday_Tuesday           0.00
weekday_Wednesday         0.00
Name: 1, dtype: float64

In [27]:
rfc_predictions = rfc.predict(X)
df_true_vs_rfc_predicted = pd.DataFrame({'ActualClass': y, 'PredictedClass': rfc_predictions})
df_true_vs_rfc_predicted

      ActualClass  PredictedClass
0               1               1
1               1               1
2               1               1
3               1               1
4               1               1
5               1               1
6               1               1
7               1               1
8               1               1
9               1               1
10              1               1
11              1               1
12              1               1
13              1               1
14              1               1
15              1               1
16              1               1
17              1               1
18              1               1
19              1               1
20              1               1
21              1               1
22              2               2
23              3               3
24              3               3
25              4               4
26              4               4
27              5               5
28              5               5
29              5               5
...           ...             ...
1007           15              15
1008           13              13
1009           13              13
1010           11              11
1011           12              12
1012           14              14
1013           11              11
1014           10              10
1015            9               9
1016            9               9
1017           11              11
1018           10              10
1019           10              10
1020           11              11
1021           12              12
1022           10              10
1023            9               9
1024            7               7
1025            7               7
1026            7               7
1027            6               6
1028            4               4
1029            3               3
1030            0               0
1031            1               1
1032            2               2
1033            0               0
1034            0               0
1035            1               1
1036            0               0

[1037 rows x 2 columns]

In [28]:
print("Accuracy: ", metrics.accuracy_score(y, rfc_predictions))
print("Confusion matrix: \n", metrics.confusion_matrix(y, rfc_predictions))
print("Classification report:\n ", metrics.classification_report(y, rfc_predictions))

Accuracy:  1.0
Confusion matrix:
 [[126   0   0 ...,   0   0   0]
 [  0  36   0 ...,   0   0   0]
 [  0   0  24 ...,   0   0   0]
 ...,
 [  0   0   0 ...,  25   0   0]
 [  0   0   0 ...,   0  49   0]
 [  0   0   0 ...,   0   0 104]]
Classification report:
               precision    recall  f1-score   support

          0       1.00      1.00      1.00       126
          1       1.00      1.00      1.00        36
          2       1.00      1.00      1.00        24
          3       1.00      1.00      1.00        22
          4       1.00      1.00      1.00        16
          5       1.00      1.00      1.00        17
          6       1.00      1.00      1.00        19
          7       1.00      1.00      1.00        19
          8       1.00      1.00      1.00        24
          9       1.00      1.00      1.00        35
         10       1.00      1.00      1.00        57
         11       1.00      1.00      1.00        28
         12       1.00      1.00      1.00        32
         13       1.00      1.00      1.00        28
         14       1.00      1.00      1.00        26
         15       1.00      1.00      1.00        19
         16       1.00      1.00      1.00        27
         17       1.00      1.00      1.00        17
         18       1.00      1.00      1.00        27
         19       1.00      1.00      1.00        53
         20       1.00      1.00      1.00        36
         21       1.00      1.00      1.00        26
         22       1.00      1.00      1.00        28
         23       1.00      1.00      1.00        23
         24       1.00      1.00      1.00        27
         25       1.00      1.00      1.00        18
         26       1.00      1.00      1.00        14
         27       1.00      1.00      1.00        18
         28       1.00      1.00      1.00        17
         29       1.00      1.00      1.00        25
         30       1.00      1.00      1.00        49
         31       1.00      1.00      1.00       104

avg / total       1.00      1.00      1.00      1037

In [29]:
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=True, random_state=1, verbose=0, warm_start=False)

In [30]:
rfc_predictions_test = rfc.predict(X_test)
df_true_vs_rfc_predicted_test = pd.DataFrame({'ActualClass': y_test, 'PredictedClass': rfc_predictions_test})
df_true_vs_rfc_predicted_test

      ActualClass  PredictedClass
782             0               1
330            19              19
730            26              23
278            23              22
208            27              30
985            13              14
19              1               1
733            20              22
129            13              13
863            12              13
900            27              26
862            11               9
585             9              10
1016            9               9
35             14              14
455             4               5
100            10              13
927            31              30
848             0               0
691            15              15
238            30              31
840             0               0
794            16              16
182            10              10
170            10              10
378            31              31
833             0               0
442             6               5
843             0               0
107            10               9
...           ...             ...
63             31              30
162            10              11
374            31              31
544             0               0
481             0               0
916            29              28
513             0               2
921            31              31
424             8               8
155            18              19
1032            2               1
1035            1               0
608             9              11
183            10              10
12              1               1
546             0               0
905            31              31
966            12              10
752            11               8
996            18              18
917            29              28
425             8               8
169            10              10
714            17              16
926            31              30
42             10              10
405            31              31
811             3               3
470             2               2
906            31              31

[312 rows x 2 columns]

In [31]:
print("Accuracy: ", metrics.accuracy_score(y_test, rfc_predictions_test))
print("Confusion matrix: \n", metrics.confusion_matrix(y_test, rfc_predictions_test))
print("Classification report:\n ", metrics.classification_report(y_test, rfc_predictions_test))

Accuracy:  0.448717948718
Confusion matrix:
 [[31  3  3 ...,  0  0  0]
 [ 7  7  2 ...,  0  0  0]
 [ 2  1  4 ...,  0  0  0]
 ...,
 [ 0  0  0 ...,  3  0  0]
 [ 0  0  0 ...,  4  3  9]
 [ 0  0  0 ...,  1  7 16]]
Classification report:
               precision    recall  f1-score   support

          0       0.78      0.82      0.79        38
          1       0.64      0.44      0.52        16
          2       0.29      0.44      0.35         9
          3       0.71      0.71      0.71         7
          4       0.33      0.25      0.29         4
          5       0.50      0.57      0.53         7
          6       0.14      0.25      0.18         4
          7       0.00      0.00      0.00         8
          8       0.25      0.38      0.30         8
          9       0.40      0.31      0.35        13
         10       0.54      0.72      0.62        18
         11       0.00      0.00      0.00         4
         12       0.75      0.20      0.32        15
         13       0.50      0.42      0.45        12
         14       0.27      0.44      0.33         9
         15       0.33      0.33      0.33         6
         16       0.20      0.12      0.15         8
         17       0.20      0.17      0.18         6
         18       0.25      0.67      0.36         3
         19       0.76      0.73      0.74        22
         20       0.12      0.17      0.14         6
         21       0.40      0.40      0.40         5
         22       0.00      0.00      0.00         7
         23       0.29      0.22      0.25         9
         24       0.33      0.43      0.38         7
         25       0.00      0.00      0.00         5
         26       0.25      0.33      0.29         3
         27       0.50      0.25      0.33         4
         28       0.25      0.25      0.25         4
         29       0.38      0.60      0.46         5
         30       0.25      0.19      0.21        16
         31       0.62      0.67      0.64        24

avg / total       0.46      0.45      0.44       312

In [32]:
# compute the out-of-bag classification accuracy
rfc.oob_score_

0.43448275862068964

In [33]:
for i in range(10,110,10):
    print(i)
    rfc = RandomForestClassifier(n_estimators=i, max_features='auto', oob_score=True)
    rfc.fit(X_train, y_train)
    rfc_predictions_test = rfc.predict(X_test)
    print("Accuracy: ", metrics.accuracy_score(y_test, rfc_predictions_test))
    rfc.oob_score_

10
Accuracy:  0.432692307692
20
Accuracy:  0.461538461538
30
Accuracy:  0.448717948718

/Users/yaoxuanchen/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/forest.py:453: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
/Users/yaoxuanchen/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/forest.py:458: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])

40
Accuracy:  0.471153846154
50
Accuracy:  0.448717948718
60
Accuracy:  0.451923076923
70
Accuracy:  0.445512820513
80
Accuracy:  0.445512820513
90
Accuracy:  0.455128205128
100
Accuracy:  0.461538461538

In [34]:
cur = conn.cursor()
cur.execute('select * from station_1 ORDER BY last_update DESC limit 0, 1')
detailData = cur.fetchone()
detailData[0].minute

20

In [35]:
X.columns

Index(['humidity', 'temp', 'wind', 'month', 'day', 'hour', 'minute',
       'pre_minute', 'pre_hour', 'pre_available_bikes', 'weather_main_Clear',
       'weather_main_Clouds', 'weather_main_Drizzle', 'weather_main_Fog',
       'weather_main_Mist', 'weather_main_Rain', 'weekday_Friday',
       'weekday_Monday', 'weekday_Saturday', 'weekday_Sunday',
       'weekday_Thursday', 'weekday_Tuesday', 'weekday_Wednesday'],
      dtype='object')

In [36]:
import mysql.connector
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from patsy import dmatrices
from sklearn.cross_validation import train_test_split
from sklearn import metrics
from sklearn.cross_validation import cross_val_score
from sklearn.tree import export_graphviz
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

rds_host='mybike.c0jxuz6r8olg.us-west-2.rds.amazonaws.com'
name='hibike'
pwd='zx123456'
db_name='bike'
port=3306


import pandas as pd
import requests
from datetime import datetime

In [38]:
diCol = [x for x in X.columns]
di = rfc

In [39]:
conn = mysql.connector.connect(host=rds_host,user=name, password=pwd, database=db_name)

cur = conn.cursor()
cur.execute("select * from Bike_Stations")
stationData = cur.fetchall()

import datetime
PredictTime = 1
stationNum = 2
cur.execute('select * from station_1 ORDER BY last_update DESC limit 0, 1')
detailData = cur.fetchone()
cur.execute('select * from weather ORDER BY last_update DESC limit 0, 1')
weatherData = cur.fetchone()
diCol_pr = {}
global diCol
global di
print(len(diCol))
print(len(diCol_pr))
futTime = ((datetime.datetime.now() - weatherData[0]).total_seconds() / 60 ) + float(PredictTime)
print(futTime)
print(datetime.datetime.now().month, datetime.datetime.now().day, datetime.datetime.now().hour, datetime.datetime.now().minute)
if (futTime > 180) :
    stationNum = int(stationNum)
    print('>180')
    try:
        for i in diCol[stationNum]:
            diCol_pr[i] = 0
        r_w = requests.get('http://api.openweathermap.org/data/2.5/forecast?q=Dublin,IE&APPID=7b3e054e55cf81602b4298ca04a0fa18')

        diCol_pr['pre_available_bikes'] = detailData[-1]
        diCol_pr['pre_hour'] = detailData[0].hour
        diCol_pr['pre_minute'] = detailData[0].minute

        diCol_pr['month'] = datetime.datetime.now().month + (datetime.datetime.now().day + (datetime.datetime.now().hour + PredictTime // 60) // 24) // 30
        diCol_pr['day'] = datetime.datetime.now().day + PredictTime + (datetime.datetime.now().hour + PredictTime // 60) // 24
        diCol_pr['hour'] = datetime.datetime.now().hour + PredictTime // 60
        diCol_pr['minute'] = datetime.datetime.now().minute + datetime.datetime.now().hour * 60 + PredictTime 
        diCol_pr['humidity'] = r_w.json()['list'][0]['main']['humidity']
        diCol_pr['temp'] = r_w.json()['list'][0]['main']['temp']
        diCol_pr['wind'] = r_w.json()['list'][0]['wind']['speed']
        weekday = datetime.datetime.now().weekday() + PredictTime + (datetime.datetime.now().hour + PredictTime // 60) // 24
        if weekday >= 7:
            weekday = 0

        weather = r_w.json()['list'][0]['weather'][0]['main']
        print(weather)
        weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
        weekday = weekdays[weekday]
        if 'weather_main_{}'.format(weather) in diCol_pr.keys():
            diCol_pr['weather_main_{}'.format(weather)] = 1
            if 'weekday_{}'.format(weekday) in diCol_pr.keys():
                diCol_pr['weekday_{}'.format(weekday)] = 1

                predi = pd.DataFrame([diCol_pr])
                rfc_predictions = "available_bikes : {}".format(int(di.predict(predi)))
                print(rfc_predictions , diCol_pr, diCol[stationNum])
            else:
                rfc_predictions = "Something wrong, day information get error."
        else:
            rfc_predictions = "A new weather may appear, not enough data to make a prediction."
    except Exception as e:
        rfc_predictions = "We rebuild the prediction module, please try 10 minutes late."
else :
    print('<180')
    stationNum = int(stationNum)
    print(len(diCol))
    for i in diCol:
        diCol_pr[i] = 0
    print(diCol_pr)
    print(diCol)
    diCol_pr['pre_available_bikes'] = detailData[-1]
    diCol_pr['pre_hour'] = detailData[0].hour
    diCol_pr['pre_minute'] = detailData[0].minute

    diCol_pr['month'] = datetime.datetime.now().month + (datetime.datetime.now().day + (datetime.datetime.now().hour + (datetime.datetime.now().minute + PredictTime) // 60) // 24) // 30
    diCol_pr['day'] = datetime.datetime.now().day + (datetime.datetime.now().hour + (datetime.datetime.now().minute + PredictTime) // 60) // 24
    diCol_pr['hour'] = datetime.datetime.now().hour + (datetime.datetime.now().minute + PredictTime) // 60
    diCol_pr['minute'] = (datetime.datetime.now().minute + PredictTime) % 60

    diCol_pr['humidity'] = float(weatherData[2])
    diCol_pr['temp'] = weatherData[3]
    diCol_pr['wind'] = weatherData[5]

    weekday = datetime.datetime.now().weekday() + (datetime.datetime.now().hour + (datetime.datetime.now().minute + PredictTime) // 60) // 24
    if weekday >= 7:
        weekday = 0
    weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    weekday = weekdays[weekday]
    weather = weatherData[1]
    print(weather)
    if 'weather_main_{}'.format(weather) in diCol_pr.keys():
        diCol_pr['weather_main_{}'.format(weather)] = 1
        if 'weekday_{}'.format(weekday) in diCol_pr.keys():
            diCol_pr['weekday_{}'.format(weekday)] = 1                  
            predi = pd.DataFrame([diCol_pr])
            print(rfc.predict(predi))
            print('work')
            rfc_predictions = "available_bikes : {}".format(int(di.predict(predi)))
            print(rfc_predictions , diCol_pr, diCol[stationNum])
        else:
            rfc_predictions = "Something wrong, day information get error."
    else:
        rfc_predictions = "A new weather may appear, not enough data to make a prediction."

23
0
25.486567316666665
4 19 20 24
<180
23
{'humidity': 0, 'temp': 0, 'wind': 0, 'month': 0, 'day': 0, 'hour': 0, 'minute': 0, 'pre_minute': 0, 'pre_hour': 0, 'pre_available_bikes': 0, 'weather_main_Clear': 0, 'weather_main_Clouds': 0, 'weather_main_Drizzle': 0, 'weather_main_Fog': 0, 'weather_main_Mist': 0, 'weather_main_Rain': 0, 'weekday_Friday': 0, 'weekday_Monday': 0, 'weekday_Saturday': 0, 'weekday_Sunday': 0, 'weekday_Thursday': 0, 'weekday_Tuesday': 0, 'weekday_Wednesday': 0}
['humidity', 'temp', 'wind', 'month', 'day', 'hour', 'minute', 'pre_minute', 'pre_hour', 'pre_available_bikes', 'weather_main_Clear', 'weather_main_Clouds', 'weather_main_Drizzle', 'weather_main_Fog', 'weather_main_Mist', 'weather_main_Rain', 'weekday_Friday', 'weekday_Monday', 'weekday_Saturday', 'weekday_Sunday', 'weekday_Thursday', 'weekday_Tuesday', 'weekday_Wednesday']
Clouds
[0]
work
available_bikes : 0 {'humidity': 67.0, 'temp': 288.15, 'wind': 4.6, 'month': 4, 'day': 19, 'hour': 20, 'minute': 25, 'pre_minute': 20, 'pre_hour': 20, 'pre_available_bikes': 0, 'weather_main_Clear': 0, 'weather_main_Clouds': 1, 'weather_main_Drizzle': 0, 'weather_main_Fog': 0, 'weather_main_Mist': 0, 'weather_main_Rain': 0, 'weekday_Friday': 1, 'weekday_Monday': 0, 'weekday_Saturday': 0, 'weekday_Sunday': 0, 'weekday_Thursday': 0, 'weekday_Tuesday': 0, 'weekday_Wednesday': 0} wind

In [ ]:
cur.execute('select * from station_1 ORDER BY last_update DESC limit 0, 1')
detailData = cur.fetchone()
detailData

In [ ]:
import json, requests
from datetime import datetime

r_w = requests.get('http://api.openweathermap.org/data/2.5/forecast?q=Dublin,IE&APPID=7b3e054e55cf81602b4298ca04a0fa18')

di = {x : 0 for x in sorted(X.columns)}

di['pre_available_bikes'] = detailData[-1]
di['pre_minute'] = detailData[0].minute

di['month'] = datetime.utcfromtimestamp(r_w.json()['list'][0]['dt']).month
di['day'] = datetime.utcfromtimestamp(r_w.json()['list'][0]['dt']).day
di['hour'] = datetime.utcfromtimestamp(r_w.json()['list'][0]['dt']).hour
di['humidity'] = r_w.json()['list'][0]['main']['humidity']
di['minute'] = datetime.utcfromtimestamp(r_w.json()['list'][0]['dt']).minute
di['temp'] = r_w.json()['list'][0]['main']['temp']
di['wind'] = r_w.json()['list'][0]['wind']['speed']

weather = r_w.json()['list'][0]['weather'][0]['main']
weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday',
            'Friday', 'Saturday', 'Sunday']
weekday = weekdays[datetime.utcfromtimestamp(r_w.json()['list'][0]['dt']).weekday()]
if 'weather_main_{}'.format(weather) in di:
    di['weather_main_{}'.format(weather)] = 1
if 'weekday_{}'.format(weekday) in di:
    di['weekday_{}'.format(weekday)] = 1

In [ ]:
predi = pd.DataFrame([di])
predi

In [ ]:
rfc_predictions = rfc.predict(predi)
print(rfc_predictions)