In [357]:
import mysql.connector
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from patsy import dmatrices
from sklearn.cross_validation import train_test_split
from sklearn import metrics
from sklearn.cross_validation import cross_val_score
from sklearn.tree import export_graphviz
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [358]:
rds_host='mybike.c0jxuz6r8olg.us-west-2.rds.amazonaws.com'
name='hibike'
pwd='zx123456'
db_name='bike'
port=3306

conn = mysql.connector.connect(host=rds_host,user=name, password=pwd, database=db_name)

In [359]:
df = pd.read_sql("select * from weather", con=conn)
df1 = pd.read_sql("select * from station_60", con=conn)
df.shape

(318, 6)

In [360]:
df['month'] = df['last_update'].dt.month
df['day'] = df['last_update'].dt.day
df['weekday'] = df['last_update'].dt.weekday_name
df['hour'] = df['last_update'].dt.hour
df['minute'] = df['last_update'].dt.minute

df1['month'] = df1['last_update'].dt.month
df1['day'] = df1['last_update'].dt.day
df1['weekday'] = df1['last_update'].dt.weekday_name
df1['hour'] = df1['last_update'].dt.hour
df1['minute'] = df1['last_update'].dt.minute

In [361]:
df1.minute = (df1.minute > 30) *30

In [362]:
df2 = pd.merge(df, df1, left_on=['minute', 'hour', 'weekday', 'month', 'day'], right_on=['minute', 'hour', 'weekday', 'month', 'day'])

In [363]:
df2 = df2.drop(['last_update_x'] , axis=1)

In [364]:
categorical_columns = df2[['weather_main', 'weekday', 'status']]
for column in categorical_columns:
    df2[column] = df2[column].astype('category')
df2.select_dtypes(['category']).describe().T

             count unique        top  freq
weather_main  1062      6     Clouds   780
weekday       1062      7  Wednesday   264
status        1062      1       OPEN  1062

In [365]:
# Select columns containing continuous data
continuous_columns = []
for column in df2.columns.values:
    if column not in categorical_columns:
        continuous_columns.append(column)
df2['humidity'] = df2['humidity'].astype('float')

continuous_columns.pop(continuous_columns.index('last_update_y'))
print(df2[continuous_columns].dtypes)

humidity                 float64
temp                     float64
visibility               float64
wind                     float64
month                      int64
day                        int64
hour                       int64
minute                     int64
bike_stands                int64
available_bike_stands      int64
available_bikes            int64
dtype: object

In [366]:
#df2['pre_available_bikes'][0] = df2['available_bikes'][0]
#df2['pre_available_bikes'].iloc[1:] = df2['available_bikes'][:-1]
#pd.concat([df2['available_bikes'][0:1], df2['available_bikes'][:-1]])

pre_bikes = df2['available_bikes'][:-1].tolist()
pre_bikes.insert(0, df2['available_bikes'][0])
df2['pre_bikes'] = pre_bikes
df2['pre_bikes'].describe().T

count    1062.000000
mean       15.472693
std        10.549587
min         0.000000
25%         6.000000
50%        16.000000
75%        26.000000
max        30.000000
Name: pre_bikes, dtype: float64

In [367]:
ti = pd.DataFrame({'current': df2['last_update_y'][1:].tolist(), 'now': (df2['last_update_y'][:-1].tolist())})
Las_now_minute = (ti.current - ti.now).tolist()
Las_now_minute.insert(0, np.timedelta64(9, 'm'))
df2['Las_now_minute'] = Las_now_minute
df2['Las_now_minute'] = df2['Las_now_minute'] / np.timedelta64(1, 'm')
df2['ratio'] = df2['pre_bikes'] / ( df2['Las_now_minute'] * 10)
continuous_columns.append('ratio')

In [368]:
df_dummies_weather_main = pd.get_dummies(df2[['weather_main']])
print(df_dummies_weather_main.head())
df_dummies_weekday = pd.get_dummies(df2[['weekday']])
df_dummies_weekday.head()

   weather_main_Clear  weather_main_Clouds  weather_main_Drizzle  \
0                   0                    0                     1
1                   0                    0                     1
2                   0                    0                     1
3                   0                    0                     1
4                   0                    0                     1

   weather_main_Fog  weather_main_Mist  weather_main_Rain
0                 0                  0                  0
1                 0                  0                  0
2                 0                  0                  0
3                 0                  0                  0
4                 0                  0                  0

,weekday_Friday,weekday_Monday,weekday_Saturday,weekday_Sunday,weekday_Thursday,weekday_Tuesday,weekday_Wednesday
0,1,0,0,0,0,0,0
1,1,0,0,0,0,0,0
2,1,0,0,0,0,0,0
3,1,0,0,0,0,0,0
4,1,0,0,0,0,0,0

In [369]:
describe_columns = [x for x in continuous_columns if x not in ['available_bike_stands', 'bike_stands', 'available_bikes', 'visibility', 'day', 'month']]
describe_columns

['humidity', 'temp', 'wind', 'hour', 'minute', 'ratio']

In [370]:
X = pd.concat([df2[describe_columns], df_dummies_weather_main, df_dummies_weekday], axis =1)
y = df2.available_bikes
X

,humidity,temp,wind,hour,minute,ratio,weather_main_Clear,weather_main_Clouds,weather_main_Drizzle,weather_main_Fog,weather_main_Mist,weather_main_Rain,weekday_Friday,weekday_Monday,weekday_Saturday,weekday_Sunday,weekday_Thursday,weekday_Tuesday,weekday_Wednesday
0,93.0,280.15,4.1,1,0,0.026667,0,0,1,0,0,0,1,0,0,0,0,0,0
1,93.0,280.15,4.1,1,0,0.023645,0,0,1,0,0,0,1,0,0,0,0,0,0
2,93.0,280.15,3.1,1,30,0.023645,0,0,1,0,0,0,1,0,0,0,0,0,0
3,93.0,280.15,3.1,1,30,0.023645,0,0,1,0,0,0,1,0,0,0,0,0,0
4,93.0,280.15,3.1,1,30,0.023607,0,0,1,0,0,0,1,0,0,0,0,0,0
5,93.0,280.15,3.6,2,0,0.023645,0,0,1,0,0,0,1,0,0,0,0,0,0
6,93.0,280.15,3.6,2,0,0.023645,0,0,1,0,0,0,1,0,0,0,0,0,0
7,93.0,280.15,3.6,2,0,0.023645,0,0,1,0,0,0,1,0,0,0,0,0,0
8,93.0,280.15,3.6,2,30,0.023645,0,0,1,0,0,0,1,0,0,0,0,0,0
9,93.0,280.15,3.6,2,30,0.023684,0,0,1,0,0,0,1,0,0,0,0,0,0
10,93.0,280.15,3.6,2,30,0.023607,0,0,1,0,0,0,1,0,0,0,0,0,0
11,93.0,280.15,3.1,3,0,0.023645,0,0,1,0,0,0,1,0,0,0,0,0,0
12,93.0,280.15,3.1,3,0,0.023645,0,0,1,0,0,0,1,0,0,0,0,0,0
13,100.0,279.72,3.1,3,30,0.016036,0,0,1,0,0,0,1,0,0,0,0,0,0
14,100.0,279.72,3.1,3,30,0.128571,0,0,1,0,0,0,1,0,0,0,0,0,0
15,100.0,279.72,3.1,3,30,0.023607,0,0,1,0,0,0,1,0,0,0,0,0,0
16,100.0,279.72,3.1,3,30,0.023684,0,0,1,0,0,0,1,0,0,0,0,0,0
17,100.0,279.66,3.1,4,0,0.023607,0,0,1,0,0,0,1,0,0,0,0,0,0
18,100.0,279.66,3.1,4,0,0.023645,0,0,1,0,0,0,1,0,0,0,0,0,0
19,100.0,279.66,3.1,4,0,0.023645,0,0,1,0,0,0,1,0,0,0,0,0,0
20,100.0,279.77,2.6,5,0,0.006578,0,0,1,0,0,0,1,0,0,0,0,0,0
21,100.0,279.77,2.6,5,0,0.023645,0,0,1,0,0,0,1,0,0,0,0,0,0
22,100.0,279.77,2.6,5,0,0.037598,0,0,1,0,0,0,1,0,0,0,0,0,0
23,100.0,279.77,2.6,5,0,0.019355,0,0,1,0,0,0,1,0,0,0,0,0,0
24,100.0,279.71,3.1,5,30,0.069110,0,0,1,0,0,0,1,0,0,0,0,0,0
25,100.0,279.71,3.1,5,30,0.020690,0,0,1,0,0,0,1,0,0,0,0,0,0
26,100.0,279.71,3.1,5,30,0.032086,0,0,1,0,0,0,1,0,0,0,0,0,0
27,100.0,279.77,3.6,6,0,0.013992,0,0,1,0,0,0,1,0,0,0,0,0,0
28,100.0,279.77,3.6,6,0,0.053892,0,0,1,0,0,0,1,0,0,0,0,0,0
29,100.0,279.77,3.6,6,0,0.013793,0,0,1,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1032,71.0,287.71,5.1,20,30,0.040637,0,1,0,0,0,0,0,0,0,0,1,0,0
1033,71.0,287.71,5.1,20,30,0.029825,0,1,0,0,0,0,0,0,0,0,1,0,0
1034,71.0,287.71,5.1,20,30,0.071429,0,1,0,0,0,0,0,0,0,0,1,0,0
1035,76.0,287.77,5.7,21,0,0.033994,0,1,0,0,0,0,0,0,0,0,1,0,0
1036,76.0,287.77,5.7,21,0,0.043321,0,1,0,0,0,0,0,0,0,0,1,0,0
1037,76.0,287.77,5.7,21,0,0.226415,0,1,0,0,0,0,0,0,0,0,1,0,0
1038,76.0,287.77,5.7,21,0,0.040569,0,1,0,0,0,0,0,0,0,0,1,0,0
1039,76.0,287.77,5.7,21,0,0.056338,0,1,0,0,0,0,0,0,0,0,1,0,0
1040,76.0,287.77,5.7,21,0,0.102222,0,1,0,0,0,0,0,0,0,0,1,0,0
1041,76.0,287.77,5.7,21,0,0.056693,0,1,0,0,0,0,0,0,0,0,1,0,0
1042,76.0,287.77,5.7,21,0,0.112230,0,1,0,0,0,0,0,0,0,0,1,0,0
1043,82.0,285.59,3.6,21,30,0.029658,0,1,0,0,0,0,0,0,0,0,1,0,0
1044,82.0,285.59,3.6,21,30,0.078000,0,1,0,0,0,0,0,0,0,0,1,0,0
1045,82.0,285.59,3.6,21,30,0.054194,0,1,0,0,0,0,0,0,0,0,1,0,0
1046,82.0,285.59,3.6,21,30,0.028525,0,1,0,0,0,0,0,0,0,0,1,0,0
1047,87.0,284.64,3.6,22,0,0.027707,0,1,0,0,0,0,0,0,0,0,1,0,0
1048,87.0,284.64,3.6,22,0,0.051327,0,1,0,0,0,0,0,0,0,0,1,0,0
1049,87.0,284.64,3.6,22,0,0.102273,0,1,0,0,0,0,0,0,0,0,1,0,0
1050,87.0,284.64,3.6,22,0,0.028571,0,1,0,0,0,0,0,0,0,0,1,0,0
1051,87.0,284.64,3.6,22,0,0.238356,0,1,0,0,0,0,0,0,0,0,1,0,0
1052,81.0,284.58,2.6,22,30,0.029557,0,1,0,0,0,0,0,0,0,0,1,0,0
1053,81.0,284.58,2.6,22,30,0.029557,0,1,0,0,0,0,0,0,0,0,1,0,0
1054,81.0,284.58,2.6,22,30,0.025140,0,1,0,0,0,0,0,0,0,0,1,0,0
1055,81.0,284.64,4.1,23,0,0.029508,0,1,0,0,0,0,0,0,0,0,1,0,0
1056,81.0,284.64,4.1,23,0,0.029557,0,1,0,0,0,0,0,0,0,0,1,0,0
1057,81.0,284.64,4.1,23,0,0.030303,0,1,0,0,0,0,0,0,0,0,1,0,0
1058,81.0,284.64,4.1,23,0,0.120805,0,1,0,0,0,0,0,0,0,0,1,0,0
1059,81.0,284.58,4.6,23,30,0.017549,0,1,0,0,0,0,0,0,0,0,1,0,0
1060,81.0,284.58,4.6,23,30,0.020656,0,1,0,0,0,0,0,0,0,0,1,0,0
1061,81.0,284.58,4.6,23,30,0.466667,0,1,0,0,0,0,0,0,0,0,1,0,0

In [371]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

print("Training data:\n", pd.concat([X_train, y_train], axis=1))
print("\nTest data:\n", pd.concat([X_test, y_test], axis=1))

Training data:
       humidity    temp  wind  hour  minute     ratio  weather_main_Clear  \
161      100.0  281.16   3.1    23       0  0.022606                   0
39       100.0  279.15   3.1     7       0  0.001210                   0
573       81.0  284.15   4.1     2       0  0.027541                   0
33       100.0  279.15   3.1     6      30  0.009658                   0
910       72.0  287.64   4.6    10       0  0.000000                   0
409       93.0  282.72  10.8    12      30  0.000000                   0
907       72.0  287.64   4.6    10       0  0.001354                   0
561       81.0  284.15   4.6     0      30  0.110294                   0
262       81.0  285.31   7.2    14      30  0.060465                   0
529       71.0  284.64   9.3    21       0  0.029508                   0
225       81.0  284.15   5.1    10       0  0.019672                   0
289       76.0  284.77   7.7    18       0  0.011278                   0
1014      55.0  290.64   2.6    18       0  0.400000                   0
354       93.0  281.66   8.7     4       0  0.015764                   0
807       71.0  286.58   8.7    22      30  0.031441                   0
83        87.0  281.66   1.5    13       0  0.006963                   0
1027      67.0  288.15   4.6    20       0  0.236842                   0
479       81.0  283.15   5.1    23       0  0.021927                   0
34       100.0  279.15   3.1     6      30  0.010256                   0
374       87.0  282.15  10.3     7      30  0.010526                   0
1011      55.0  290.64   2.6    18       0  0.061224                   0
553       81.0  284.15   5.1    23      30  0.061972                   0
62        93.0  280.15   3.1    10       0  0.000000                   0
413       93.0  282.66  10.8    13       0  0.002073                   0
355      100.0  281.72   6.7     4      30  0.015764                   0
185       75.0  281.15   3.6     3      30  0.029557                   1
887       93.0  285.16   4.6     8       0  0.074157                   0
989       52.0  291.15   4.1    16      30  0.042975                   0
6         93.0  280.15   3.6     2       0  0.023645                   0
1053      81.0  284.58   2.6    22      30  0.029557                   0
...        ...     ...   ...   ...     ...       ...                 ...
54       100.0  279.15   4.1     9       0  0.026087                   0
327       87.0  282.15   5.7    23      30  0.010837                   0
848       93.0  282.87   1.5     4      30  0.023645                   0
386       93.0  282.72  10.8     9      30  0.001014                   0
584       93.0  284.30   5.1     3      30  0.027496                   0
991       52.0  291.15   4.6    17       0  0.098824                   0
567       81.0  284.15   7.2     1       0  0.027541                   0
525       71.0  285.15   8.7    20      30  0.027541                   0
817       71.0  286.58   5.7    23      30  0.021639                   0
305       87.0  282.72   5.7    20      30  0.022222                   0
759       59.0  290.72   9.3    18      30  0.029412                   0
594       93.0  284.17   3.1     5       0  0.430769                   0
229       87.0  283.72   6.2    10      30  0.019883                   0
279       76.0  284.72   7.2    16      30  0.025806                   0
453       93.0  283.29   7.7    19      30  0.002140                   0
575       93.0  283.72   4.1     2      30  0.027541                   0
428       93.0  283.29  10.3    15      30  0.004278                   0
968       55.0  290.15   6.7    15      30  0.044882                   0
371       87.0  282.15  10.3     7      30  0.025882                   0
55       100.0  279.15   4.1     9       0  0.005139                   0
589       93.0  283.72   3.6     4      30  0.027406                   0
533       71.0  284.58   8.2    21      30  0.195652                   0
353       93.0  281.66   8.7     4       0  0.015764                   0
269       81.0  284.73   8.2    15      30  0.016119                   0
825       81.0  285.15   4.1     0      30  0.023607                   0
790       62.0  287.14   7.7    21       0  0.120000                   0
287       76.0  284.77   7.7    18       0  0.076744                   0
1044      82.0  285.59   3.6    21      30  0.078000                   0
834       81.0  284.64   3.1     2       0  0.023645                   0
93        87.0  281.66   1.5    14      30  0.012935                   0

      weather_main_Clouds  weather_main_Drizzle  weather_main_Fog  \
161                     1                     0                 0
39                      0                     1                 0
573                     1                     0                 0
33                      0                     1                 0
910                     1                     0                 0
409                     0                     1                 0
907                     1                     0                 0
561                     1                     0                 0
262                     1                     0                 0
529                     1                     0                 0
225                     0                     0                 0
289                     1                     0                 0
1014                    1                     0                 0
354                     0                     0                 1
807                     1                     0                 0
83                      1                     0                 0
1027                    1                     0                 0
479                     1                     0                 0
34                      0                     1                 0
374                     0                     0                 0
1011                    1                     0                 0
553                     1                     0                 0
62                      0                     1                 0
413                     0                     1                 0
355                     0                     0                 0
185                     0                     0                 0
887                     1                     0                 0
989                     1                     0                 0
6                       0                     1                 0
1053                    1                     0                 0
...                   ...                   ...               ...
54                      0                     1                 0
327                     1                     0                 0
848                     1                     0                 0
386                     0                     1                 0
584                     0                     0                 1
991                     1                     0                 0
567                     1                     0                 0
525                     1                     0                 0
817                     1                     0                 0
305                     1                     0                 0
759                     1                     0                 0
594                     0                     1                 0
229                     0                     0                 0
279                     1                     0                 0
453                     1                     0                 0
575                     1                     0                 0
428                     0                     0                 0
968                     1                     0                 0
371                     0                     0                 0
55                      0                     1                 0
589                     0                     1                 0
533                     1                     0                 0
353                     0                     0                 1
269                     1                     0                 0
825                     1                     0                 0
790                     1                     0                 0
287                     1                     0                 0
1044                    1                     0                 0
834                     1                     0                 0
93                      1                     0                 0

      weather_main_Mist  weather_main_Rain  weekday_Friday  weekday_Monday  \
161                   0                  0               1               0
39                    0                  0               1               0
573                   0                  0               0               0
33                    0                  0               1               0
910                   0                  0               0               0
409                   0                  0               0               0
907                   0                  0               0               0
561                   0                  0               0               0
262                   0                  0               0               0
529                   0                  0               0               0
225                   0                  1               0               0
289                   0                  0               0               0
1014                  0                  0               0               0
354                   0                  0               0               0
807                   0                  0               0               0
83                    0                  0               1               0
1027                  0                  0               0               0
479                   0                  0               0               0
34                    0                  0               1               0
374                   0                  1               0               0
1011                  0                  0               0               0
553                   0                  0               0               0
62                    0                  0               1               0
413                   0                  0               0               0
355                   1                  0               0               0
185                   0                  0               0               0
887                   0                  0               0               0
989                   0                  0               0               0
6                     0                  0               1               0
1053                  0                  0               0               0
...                 ...                ...             ...             ...
54                    0                  0               1               0
327                   0                  0               0               0
848                   0                  0               0               0
386                   0                  0               0               0
584                   0                  0               0               0
991                   0                  0               0               0
567                   0                  0               0               0
525                   0                  0               0               0
817                   0                  0               0               0
305                   0                  0               0               0
759                   0                  0               0               0
594                   0                  0               0               0
229                   0                  1               0               0
279                   0                  0               0               0
453                   0                  0               0               0
575                   0                  0               0               0
428                   0                  1               0               0
968                   0                  0               0               0
371                   0                  1               0               0
55                    0                  0               1               0
589                   0                  0               0               0
533                   0                  0               0               0
353                   0                  0               0               0
269                   0                  0               0               0
825                   0                  0               0               0
790                   0                  0               0               0
287                   0                  0               0               0
1044                  0                  0               0               0
834                   0                  0               0               0
93                    0                  0               1               0

      weekday_Saturday  weekday_Sunday  weekday_Thursday  weekday_Tuesday  \
161                  0               0                 0                0
39                   0               0                 0                0
573                  0               0                 0                0
33                   0               0                 0                0
910                  0               0                 1                0
409                  0               1                 0                0
907                  0               0                 1                0
561                  0               0                 0                0
262                  1               0                 0                0
529                  0               0                 0                1
225                  1               0                 0                0
289                  1               0                 0                0
1014                 0               0                 1                0
354                  0               1                 0                0
807                  0               0                 0                0
83                   0               0                 0                0
1027                 0               0                 1                0
479                  0               1                 0                0
34                   0               0                 0                0
374                  0               1                 0                0
1011                 0               0                 1                0
553                  0               0                 0                1
62                   0               0                 0                0
413                  0               1                 0                0
355                  0               1                 0                0
185                  1               0                 0                0
887                  0               0                 1                0
989                  0               0                 1                0
6                    0               0                 0                0
1053                 0               0                 1                0
...                ...             ...               ...              ...
54                   0               0                 0                0
327                  1               0                 0                0
848                  0               0                 1                0
386                  0               1                 0                0
584                  0               0                 0                0
991                  0               0                 1                0
567                  0               0                 0                0
525                  0               0                 0                1
817                  0               0                 0                0
305                  1               0                 0                0
759                  0               0                 0                0
594                  0               0                 0                0
229                  1               0                 0                0
279                  1               0                 0                0
453                  0               1                 0                0
575                  0               0                 0                0
428                  0               1                 0                0
968                  0               0                 1                0
371                  0               1                 0                0
55                   0               0                 0                0
589                  0               0                 0                0
533                  0               0                 0                1
353                  0               1                 0                0
269                  1               0                 0                0
825                  0               0                 1                0
790                  0               0                 0                0
287                  1               0                 0                0
1044                 0               0                 1                0
834                  0               0                 1                0
93                   0               0                 0                0

      weekday_Wednesday  available_bikes
161                   0               26
39                    0                0
573                   1               28
33                    0                6
910                   0                0
409                   0                0
907                   0                1
561                   1               27
262                   0               13
529                   0               30
225                   0               20
289                   0               10
1014                  0               30
354                   0               16
807                   1               25
83                    0                3
1027                  0               13
479                   0               24
34                    0                4
374                   0                6
1011                  0               29
553                   0               23
62                    0                0
413                   0                2
355                   0               16
185                   0               30
887                   0                9
989                   0               26
6                     0               24
1053                  0               30
...                 ...              ...
54                    0                4
327                   0               11
848                   0               24
386                   0                1
584                   1               28
991                   0               28
567                   1               28
525                   0               28
817                   1               21
305                   0               10
759                   1               30
594                   1               27
229                   0               15
279                   0               13
453                   0                4
575                   1               28
428                   0                4
968                   0               20
371                   0               10

In [372]:
# Train RF with 100 trees
rfc = RandomForestClassifier(n_estimators=100, max_features='auto', oob_score=True, random_state=1)
rfc.fit(X, y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=True, random_state=1, verbose=0, warm_start=False)

In [373]:
pd.DataFrame({'feature': X.columns, 'importance':rfc.feature_importances_})

                 feature  importance
0               humidity    0.062440
1                   temp    0.106949
2                   wind    0.091699
3                   hour    0.138803
4                 minute    0.033755
5                  ratio    0.440964
6     weather_main_Clear    0.006248
7    weather_main_Clouds    0.011261
8   weather_main_Drizzle    0.008401
9       weather_main_Fog    0.001832
10     weather_main_Mist    0.002438
11     weather_main_Rain    0.006683
12        weekday_Friday    0.008509
13        weekday_Monday    0.009651
14      weekday_Saturday    0.014508
15        weekday_Sunday    0.014411
16      weekday_Thursday    0.013788
17       weekday_Tuesday    0.008218
18     weekday_Wednesday    0.019444

In [374]:
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=True, random_state=1, verbose=0, warm_start=False)

In [375]:
rfc_predictions_test = rfc.predict(X_test)
df_true_vs_rfc_predicted_test = pd.DataFrame({'ActualClass': y_test, 'PredictedClass': rfc_predictions_test})
df_true_vs_rfc_predicted_test

      ActualClass  PredictedClass
890             3              12
723             4               2
82              6               3
256             6               6
24             21              24
761            30              30
971            18              19
483            25              25
349            16              16
679             4               0
247            10              11
620             9              11
362            16              15
4              24              24
259            15              15
168            30              30
953            13              14
1029           14              17
999            30              29
364            15              15
280            15              12
831            24              24
484            27              25
1030           16              20
334            16              16
434             3               4
1000           29              30
244            10               9
1040           24              26
638             0               0
...           ...             ...
649             1               1
340            16              16
411             2               2
734            24              26
203            22              22
456             7               5
35              2               6
756            30              29
399             0               0
375             6               3
745            27              26
310             9               9
1038           20              20
243            11               9
590            28              28
394             2               2
114            30              29
271             7               7
207            17              20
714             1               2
830            24              24
435             2               2
572            28              28
430             6               2
490            30              30
601            24              24
473            17              17
870             6               3
957            17              17
627            12              11

[319 rows x 2 columns]

In [376]:
print("Accuracy: ", metrics.accuracy_score(y_test, rfc_predictions_test))

Accuracy:  0.432601880878

In [377]:
rfc.fit(X, y)
diCol = [x for x in X.columns]

diCol

['humidity',
 'temp',
 'wind',
 'hour',
 'minute',
 'ratio',
 'weather_main_Clear',
 'weather_main_Clouds',
 'weather_main_Drizzle',
 'weather_main_Fog',
 'weather_main_Mist',
 'weather_main_Rain',
 'weekday_Friday',
 'weekday_Monday',
 'weekday_Saturday',
 'weekday_Sunday',
 'weekday_Thursday',
 'weekday_Tuesday',
 'weekday_Wednesday']

In [378]:
import datetime
a = (np.datetime64(datetime.datetime.now()) - df2['last_update_y'].values[-1])
a

numpy.timedelta64(2861241677000,'ns')

In [381]:
conn = mysql.connector.connect(host=rds_host,user=name, password=pwd, database=db_name)

cur = conn.cursor()
cur.execute("select * from Bike_Stations")
stationData = cur.fetchall()

import datetime
PredictTime = 0
stationNum = 60
cur.execute('select * from station_60 ORDER BY last_update DESC limit 0, 1')
detailData = cur.fetchone()
cur.execute('select * from weather ORDER BY last_update DESC limit 0, 1')
weatherData = cur.fetchone()
diCol_pr = {}
global diCol
global di
futTime = ((datetime.datetime.now() - weatherData[0]).total_seconds() / 60 ) + float(PredictTime)
pre_ratio = detailData[-1] / (futTime * 100)
if (futTime > 180) :
    stationNum = int(stationNum)
    try:
        for i in diCol[stationNum]:
            diCol_pr[i] = 0
        r_w = requests.get('http://api.openweathermap.org/data/2.5/forecast?q=Dublin,IE&APPID=7b3e054e55cf81602b4298ca04a0fa18')

        diCol_pr['hour'] = datetime.datetime.now().hour + (datetime.datetime.now().minute + PredictTime) // 60
        diCol_pr['minute'] = (datetime.datetime.now().minute + PredictTime) % 60 
        
        diCol_pr['humidity'] = r_w.json()['list'][0]['main']['humidity']
        diCol_pr['temp'] = r_w.json()['list'][0]['main']['temp']
        diCol_pr['wind'] = r_w.json()['list'][0]['wind']['speed']
        diCol_pr['ratio'] = pre_ratio 
        weekday = datetime.datetime.now().weekday() + (datetime.datetime.now().hour + (datetime.datetime.now().minute + PredictTime) // 60) // 24
   
        if weekday >= 7:
            weekday = 0

        weather = r_w.json()['list'][0]['weather'][0]['main']
        print(weather)
        weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
        weekday = weekdays[weekday]
        if 'weather_main_{}'.format(weatherData[1]) in diCol_pr.keys():
            diCol_pr['weather_main_{}'.format(weatherData[1])] = 1
            if 'weekday_{}'.format(weekday) in diCol_pr.keys():
                diCol_pr['weekday_{}'.format(weekday)] = 1

                predi = pd.DataFrame([diCol_pr])
                rfc_predictions = "available_bikes : {}".format(int(rfx.predict(predi)))
                print(rfc_predictions , diCol_pr, diCol[stationNum])
            else:
                rfc_predictions = "Something wrong, day information get error."
        else:
            rfc_predictions = "A new weather may appear, not enough data to make a prediction."
    except Exception as e:
        rfc_predictions = "We rebuild the prediction module, please try 10 minutes late."
else :
    stationNum = int(stationNum)
    for i in diCol:
        diCol_pr[i] = 0
        
    diCol_pr['hour'] = datetime.datetime.now().hour + (datetime.datetime.now().minute + PredictTime) // 60
    diCol_pr['minute'] = (datetime.datetime.now().minute + PredictTime) % 60

    diCol_pr['humidity'] = float(weatherData[2])
    diCol_pr['temp'] = weatherData[3]
    diCol_pr['wind'] = weatherData[5]
    diCol_pr['ratio'] = pre_ratio 

    weekday = datetime.datetime.now().weekday() + (datetime.datetime.now().hour + (datetime.datetime.now().minute + PredictTime) // 60) // 24
    if weekday >= 7:
        weekday = 0
    weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    weekday = weekdays[weekday]
    if 'weather_main_{}'.format(weatherData[1]) in diCol_pr.keys():
        diCol_pr['weather_main_{}'.format(weatherData[1])] = 1
        if 'weekday_{}'.format(weekday) in diCol_pr.keys():
            diCol_pr['weekday_{}'.format(weekday)] = 1                  
            predi = pd.DataFrame([diCol_pr])
            print(rfc.predict(predi))
            rfc_predictions = "available_bikes : {}".format(int(rfc.predict(predi)))
            print(rfc_predictions , diCol_pr)
        else:
            rfc_predictions = "Something wrong, day information get error."
    else:
        rfc_predictions = "A new weather may appear, not enough data to make a prediction."

[0]
available_bikes : 0 {'humidity': 81.0, 'temp': 284.58, 'wind': 4.6, 'hour': 0, 'minute': 40, 'ratio': 0.003567508120386361, 'weather_main_Clear': 0, 'weather_main_Clouds': 1, 'weather_main_Drizzle': 0, 'weather_main_Fog': 0, 'weather_main_Mist': 0, 'weather_main_Rain': 0, 'weekday_Friday': 1, 'weekday_Monday': 0, 'weekday_Saturday': 0, 'weekday_Sunday': 0, 'weekday_Thursday': 0, 'weekday_Tuesday': 0, 'weekday_Wednesday': 0}

In [380]:
a / np.timedelta64(1, 'm')

47.687361283333331