<font size=5>1.Prepare a data quality report for the CSV file.</font>

In [157]:
# Import pandas, numpy and matplotlib libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from matplotlib.backends.backend_pdf import PdfPages
%matplotlib inline

In [158]:
mydata = pd.read_csv('CustomerChurn-16213170.csv',  keep_default_na=True, sep=',\s+', delimiter=',', skipinitialspace=True)

In [159]:
#Check how many rows and columns your CSV has.
mydata.shape

(1000, 33)

In [160]:
#Print the first 5 rows.
mydata.head(5)

,customer,age,occupation,regionType,marriageStatus,children,income,numHandsets,handsetAge,smartPhone,...,avgInCalls,peakOffPeakRatio,peakOffPeakRatioChangePct,avgDroppedCalls,lifeTime,lastMonthCustomerCareCalls,numRetentionCalls,numRetentionOffersAccepted,newFrequentNumbers,churn
0,1046755,48,professional,suburban,yes,True,7,1,421,True,...,69.33,1.867778,-11.700647,2.00,14,0.00,1,0,0,True
1,1023345,56,professional,suburban,yes,True,7,2,587,True,...,0.00,1.749064,13.662191,0.00,21,0.67,0,0,0,False
2,1067602,34,NaN,NaN,no,False,1,1,337,True,...,1.00,3.174762,19.364133,2.00,11,0.67,0,0,2,True
3,1072994,36,NaN,NaN,yes,False,7,1,240,True,...,4.33,0.835729,-5.010550,3.67,8,16.67,1,0,2,False
4,1040228,0,NaN,town,unknown,False,0,1,484,True,...,0.00,1.735710,-7.030517,1.00,16,1.67,0,0,0,False

In [161]:
#Print the first the last 5 rows.
mydata.tail(5)
mydata.dtypes

customer                        int64
age                             int64
occupation                     object
regionType                     object
marriageStatus                 object
children                         bool
income                          int64
numHandsets                     int64
handsetAge                      int64
smartPhone                       bool
currentHandsetPrice           float64
creditRating                   object
homeOwner                        bool
creditCard                     object
avgBill                       float64
avgMins                       float64
avgrecurringCharge            float64
avgOverBundleMins             float64
avgRoamCalls                  float64
callMinutesChangePct          float64
billAmountChangePct           float64
avgReceivedMins               float64
avgOutCalls                   float64
avgInCalls                    float64
peakOffPeakRatio              float64
peakOffPeakRatioChangePct     float64
avgDroppedCalls               float64
lifeTime                        int64
lastMonthCustomerCareCalls    float64
numRetentionCalls               int64
numRetentionOffersAccepted      int64
newFrequentNumbers              int64
churn                            bool
dtype: object

In [162]:
# Select columns containing categorical data
categorical_columns = mydata[['occupation','regionType','marriageStatus','income','creditRating', 'creditCard', 'children', 'smartPhone', 'homeOwner', 'churn']].columns

# Convert data type to category for these columns
for column in categorical_columns:
    mydata[column] = mydata[column].astype('category')
    
mydata.dtypes

customer                         int64
age                              int64
occupation                    category
regionType                    category
marriageStatus                category
children                      category
income                        category
numHandsets                      int64
handsetAge                       int64
smartPhone                    category
currentHandsetPrice            float64
creditRating                  category
homeOwner                     category
creditCard                    category
avgBill                        float64
avgMins                        float64
avgrecurringCharge             float64
avgOverBundleMins              float64
avgRoamCalls                   float64
callMinutesChangePct           float64
billAmountChangePct            float64
avgReceivedMins                float64
avgOutCalls                    float64
avgInCalls                     float64
peakOffPeakRatio               float64
peakOffPeakRatioChangePct      float64
avgDroppedCalls                float64
lifeTime                         int64
lastMonthCustomerCareCalls     float64
numRetentionCalls                int64
numRetentionOffersAccepted       int64
newFrequentNumbers               int64
churn                         category
dtype: object

In [163]:
mydata.select_dtypes(['category']).describe().T

               count unique           top freq
occupation       274      7  professional  174
regionType       521      7      suburban  333
marriageStatus  1000      3           yes  385
children        1000      2         False  748
income          1000     10             0  264
smartPhone      1000      2          True  902
creditRating    1000      7             B  361
homeOwner       1000      2         False  643
creditCard      1000      6          true  642
churn           1000      2         False  504

In [164]:
# Checking for duplicated rows
print(mydata.set_index('customer').index.get_duplicates())

[]

In [165]:
# Checking for duplicated columns
print(mydata.set_index('customer').index.T.get_duplicates())

[]

In [166]:
# Select columns containing continuous data
continuous_columns = []
for column in mydata.columns.values:
    if column not in categorical_columns:
        continuous_columns.append(column)
mydata[continuous_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
customer,1000.0,1.049907e+06,29377.892646,1.000022e+06,1.023521e+06,1.049796e+06,1.075653e+06,1.099988e+06
age,1000.0,2.985000e+01,22.430261,0.000000e+00,0.000000e+00,3.400000e+01,4.800000e+01,9.000000e+01
numHandsets,1000.0,1.862000e+00,1.341923,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,1.300000e+01
handsetAge,1000.0,3.899720e+02,260.183740,-2.000000e+00,2.067500e+02,3.310000e+02,5.330000e+02,1.599000e+03
currentHandsetPrice,1000.0,3.712558e+01,57.391136,0.000000e+00,0.000000e+00,0.000000e+00,5.999000e+01,2.999900e+02
avgBill,1000.0,5.870876e+01,40.375648,0.000000e+00,3.369500e+01,4.971000e+01,7.370250e+01,4.696700e+02
avgMins,1000.0,5.359519e+02,540.746586,0.000000e+00,1.587500e+02,3.720000e+02,7.361875e+02,4.530750e+03
avgrecurringCharge,1000.0,4.600562e+01,22.770386,0.000000e+00,3.000000e+01,4.499000e+01,5.919250e+01,1.699900e+02
avgOverBundleMins,1000.0,4.226150e+01,92.940958,0.000000e+00,0.000000e+00,3.500000e+00,4.575000e+01,1.389000e+03
avgRoamCalls,1000.0,1.038980e+00,4.073257,0.000000e+00,0.000000e+00,0.000000e+00,1.600000e-01,6.297000e+01
callMinutesChangePct,1000.0,-1.219282e-01,5.197377,-3.650500e+01,-1.616250e+00,-5.250000e-02,1.441250e+00,4.400500e+01
billAmountChangePct,1000.0,-5.457400e-03,0.676543,-3.964800e+00,-1.248500e-01,-5.000000e-03,3.925000e-02,5.055200e+00
avgReceivedMins,1000.0,1.193367e+02,168.939731,0.000000e+00,8.970000e+00,5.861000e+01,1.607225e+02,1.402200e+03
avgOutCalls,1000.0,2.561895e+01,32.975255,0.000000e+00,3.330000e+00,1.500000e+01,3.467000e+01,3.553300e+02
avgInCalls,1000.0,8.885900e+00,18.348180,0.000000e+00,0.000000e+00,2.165000e+00,9.330000e+00,2.836700e+02
peakOffPeakRatio,1000.0,2.018012e+00,2.664314,0.000000e+00,7.584391e-01,1.327595e+00,2.383404e+00,4.344569e+01
peakOffPeakRatioChangePct,1000.0,-5.282149e-01,9.956895,-3.577395e+01,-6.920457e+00,-2.662259e-01,5.966523e+00,3.777974e+01
avgDroppedCalls,1000.0,1.009626e+01,13.929721,0.000000e+00,2.000000e+00,6.000000e+00,1.308250e+01,1.716700e+02
lifeTime,1000.0,1.907000e+01,9.978410,6.000000e+00,1.100000e+01,1.600000e+01,2.425000e+01,5.600000e+01
lastMonthCustomerCareCalls,1000.0,2.289270e+00,12.318262,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,3.656700e+02
numRetentionCalls,1000.0,5.600000e-02,0.284508,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00
numRetentionOffersAccepted,1000.0,2.100000e-02,0.180531,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.000000e+00
newFrequentNumbers,1000.0,2.060000e-01,0.652679,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.000000e+00

In [167]:
#- Drop constant columns, if any.
columns = mydata.columns.values
for col in columns:
    # drop col if unique values is 1
    if mydata[col].nunique(dropna=False) == 1:
        del mydata[col]

In [168]:
#Save your updated/cleaned data frame to a new csv file.
mydata.to_csv('ready1.csv', index=False)

In [169]:
clean_data = pd.read_csv('ready1.csv')

In [170]:
# Check for irregular cardinality in categorical features. There could be same values spelled differently
for column in categorical_columns:
    print("Unique values for " + column + ":", pd.unique(clean_data[column].ravel()))

Unique values for occupation: ['professional' nan 'crafts' 'self-employed' 'clerical' 'homemaker'
 'retired' 'student']
Unique values for regionType: ['suburban' nan 'town' 'rural' 't' 'unknown' 's' 'r']
Unique values for marriageStatus: ['yes' 'no' 'unknown']
Unique values for income: [7 1 0 4 2 5 6 9 3 8]
Unique values for creditRating: ['E' 'B' 'A' 'D' 'F' 'C' 'G']
Unique values for creditCard: ['true' 'false' 't' 'f' 'no' 'yes']
Unique values for children: [ True False]
Unique values for smartPhone: [ True False]
Unique values for homeOwner: [False  True]
Unique values for churn: [ True False]

In [171]:
# Check whether there are null values in the data where values would be expected
clean_data.isnull().sum()

customer                        0
age                             0
occupation                    726
regionType                    479
marriageStatus                  0
children                        0
income                          0
numHandsets                     0
handsetAge                      0
smartPhone                      0
currentHandsetPrice             0
creditRating                    0
homeOwner                       0
creditCard                      0
avgBill                         0
avgMins                         0
avgrecurringCharge              0
avgOverBundleMins               0
avgRoamCalls                    0
callMinutesChangePct            0
billAmountChangePct             0
avgReceivedMins                 0
avgOutCalls                     0
avgInCalls                      0
peakOffPeakRatio                0
peakOffPeakRatioChangePct       0
avgDroppedCalls                 0
lifeTime                        0
lastMonthCustomerCareCalls      0
numRetentionCalls               0
numRetentionOffersAccepted      0
newFrequentNumbers              0
churn                           0
dtype: int64

In [172]:
#Replace the conflicting values name in  creditCard.
clean_data['creditCard'].replace('t', 'true', inplace=True) 
clean_data['creditCard'].replace('f', 'false', inplace=True)
clean_data['creditCard'].replace('no', 'false', inplace=True) 
clean_data['creditCard'].replace('yes', 'true', inplace=True) 
print("Unique values forcreditCard:", pd.unique(clean_data['creditCard'].ravel()))

Unique values forcreditCard: ['true' 'false']

In [173]:
#It seems that the empty values of occupation take 72.6%. So I decide to delete it.
clean_data = clean_data.drop('occupation', 1)

In [174]:
#It seems that the empty values of occupation take 47.9%. So I decide to delete it.
clean_data = clean_data.drop('regionType', 1)

In [175]:
clean_data = clean_data.drop('customer', 1)

In [176]:
#It seems that the empty values of occupation take 55.8% percent. So I decide to delete it.
clean_data[(clean_data['currentHandsetPrice']==0)]['currentHandsetPrice'].count()

558

In [177]:
clean_data = clean_data.drop('currentHandsetPrice', 1)

In [178]:
#说明为替换age

In [179]:
#for age
#The number of people whose age is 0 are 307. It is impossible, and it should be treaded as missing value.
clean_data[(clean_data['age']==0)]['age'].count()

307

In [180]:
print("The middle age is that will be used is: ", clean_data['age'].median())
clean_data['age'].replace(0, clean_data['age'].median(), inplace=True)
clean_data[(clean_data['age']==0)]['age'].count()

The middle age is that will be used is:  34.0

0

In [181]:
# It is impossible to fix the missing data, and it is only 38% missing data, I cannot drop it. so I replace it with NaN.
clean_data[(clean_data['marriageStatus']=='unknown')]['marriageStatus'].count()

382

In [182]:
#说明为什么删除marriagestatus

In [183]:
clean_data = clean_data.drop('marriageStatus', 1)

In [184]:
#for income
#The number of people who have 0 income are 264. It seem not so reasonable, but they are possible, for example, students
#  who have mobile and 0 income.
#Therefore, it is not possible to understand whether the data is correct or not, and I decide to keep it.
clean_data[(clean_data['income']==0)]

,age,children,income,numHandsets,handsetAge,smartPhone,creditRating,homeOwner,creditCard,avgBill,...,avgInCalls,peakOffPeakRatio,peakOffPeakRatioChangePct,avgDroppedCalls,lifeTime,lastMonthCustomerCareCalls,numRetentionCalls,numRetentionOffersAccepted,newFrequentNumbers,churn
4,34,False,0,1,484,True,E,True,false,47.93,...,0.00,1.735710,-7.030517,1.00,16,1.67,0,0,0,False
20,34,False,0,1,371,True,C,True,false,42.72,...,0.00,2.017589,-6.880538,5.67,13,4.67,0,0,0,True
22,34,False,0,1,386,True,E,True,false,69.60,...,26.67,1.105664,18.213889,31.33,13,20.67,0,0,0,True
32,34,False,0,2,18,True,C,True,false,34.99,...,0.00,4.500000,-17.347207,2.00,7,0.00,0,0,0,True
35,34,False,0,2,40,True,C,True,false,149.80,...,43.67,0.629730,-18.329509,7.00,8,0.67,0,0,0,False
36,42,False,0,1,383,True,G,True,false,60.82,...,16.67,1.289157,9.409143,8.67,13,1.00,0,0,0,False
40,34,False,0,1,199,True,C,True,false,98.53,...,4.00,0.786283,-7.077718,13.33,7,5.00,0,0,0,True
45,34,False,0,1,312,True,C,True,false,112.67,...,24.33,12.723657,-14.739520,6.33,10,0.00,0,0,0,True
46,34,False,0,1,349,True,G,True,false,50.89,...,4.00,0.584286,-7.267449,13.00,12,0.00,0,0,0,True
47,34,False,0,2,98,True,B,True,false,134.66,...,3.67,1.178275,10.609530,16.67,11,1.33,0,0,1,False
51,34,False,0,2,150,True,B,True,false,51.24,...,28.67,0.608194,13.834685,18.33,26,12.33,0,0,0,False
54,32,False,0,1,552,True,B,True,false,28.74,...,0.67,8.991826,-14.788389,1.67,19,0.00,0,0,0,True
57,34,False,0,1,404,True,B,True,false,31.32,...,1.00,3.613610,-6.618128,3.33,14,0.00,0,0,0,False
58,34,False,0,1,329,True,C,True,false,53.94,...,0.00,0.000000,18.472810,0.00,11,0.00,0,0,0,True
59,36,False,0,1,407,True,B,True,false,74.16,...,6.67,8.000000,14.097735,1.00,14,2.00,0,0,0,True
60,34,False,0,1,266,True,E,True,false,59.97,...,1.00,0.936175,-7.938771,82.33,9,5.33,0,0,2,False
63,34,False,0,2,508,True,D,True,false,109.60,...,0.33,0.650086,-8.500799,27.67,17,5.33,0,0,2,False
67,34,False,0,1,390,True,B,True,false,49.99,...,12.67,1.111927,10.470344,24.67,13,4.00,0,0,0,True
78,34,False,0,1,251,True,E,True,false,52.20,...,9.00,1.151248,12.902546,10.33,8,3.33,0,0,0,False
80,34,False,0,4,122,True,C,True,false,47.46,...,5.00,2.598775,5.807226,5.67,16,3.33,0,0,0,False
81,34,False,0,1,322,True,B,True,false,92.25,...,0.00,1.405496,1.626137,16.33,11,1.33,0,0,0,False
82,34,False,0,1,300,True,D,True,false,56.06,...,0.33,0.919616,5.587820,2.67,10,4.33,1,0,0,False
85,34,False,0,1,457,True,B,True,false,76.88,...,36.33,3.299038,8.131583,6.33,15,0.00,0,0,0,True
87,34,False,0,3,124,True,E,True,false,53.80,...,0.33,1.278372,-8.520565,2.00,12,6.33,0,0,0,True
106,34,False,0,1,187,True,D,True,false,95.44,...,7.33,0.926986,-14.231091,36.33,7,6.67,0,0,0,False
111,34,False,0,1,392,False,B,True,false,20.99,...,0.67,0.526066,-12.257285,0.00,13,0.00,0,0,0,False
129,34,False,0,3,172,True,E,True,false,136.15,...,15.67,2.852052,-4.105855,19.33,15,4.00,0,0,0,False
133,34,False,0,3,130,True,B,True,false,108.33,...,5.33,0.951787,-2.554959,10.00,18,2.33,0,0,0,False
139,34,False,0,1,322,True,B,True,false,14.82,...,15.33,1.148484,8.975087,8.33,11,0.67,0,0,0,True
143,34,False,0,3,180,True,G,True,false,38.99,...,4.33,1.113202,-9.340320,7.00,13,1.67,0,0,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
897,52,False,0,1,457,True,C,True,true,85.86,...,11.00,3.167506,-9.176830,8.00,15,0.00,0,0,3,True
901,52,False,0,1,595,True,B,True,false,32.49,...,0.33,6.223333,-3.927345,1.33,20,0.00,0,0,0,False
905,34,False,0,3,745,True,C,True,false,83.53,...,1.00,1.986511,2.379875,22.33,31,1.67,4,3,0,True
906,34,False,0,1,190,True,B,True,true,47.60,...,8.67,1.615822,3.581432,14.33,6,8.00,0,0,0,False
911,34,False,0,3,185,True,B,True,false,118.85,...,105.33,0.737861,-23.334329,10.67,20,5.00,0,0,0,False
917,34,False,0,3,102,True,C,True,false,41.73,...,6.33,0.974327,1.458952,6.33,15,0.67,0,0,0,False
925,34,False,0,2,429,False,G,True,false,38.03,...,5.00,0.701816,-0.337044,6.00,15,0.00,0,0,0,False
927,26,False,0,1,335,True,C,False,false,36.36,...,6.67,0.934070,-5.073687,1.67,11,4.67,0,0,0,False
928,34,False,0,1,655,False,D,True,false,64.26,...,0.00,1.431493,11.340476,8.67,22,0.67,0,0,0,True
930,34,False,0,2,110,True,B,True,false,134.44,...,51.33,0.993513,10.556459,38.67,16,0.33,0,0,2,False
934,34,False,0,1,198,True,E,True,false,84.58,...,4.67,1.091466,-3.569131,13.33,7,11.00,0,0,0,True
939,34,False,0,2,157,True,C,True,false,58.08,...,31.67,1.436508,27.464551,12.67,16,1.67,0,0,0,True
942,34,False,0,1,344,True,E,True,false,50.58,...,23.67,1.616279,5.708630,9.00,12,0.67,0,0,0,False
944,34,False,0,1,306,True,B,True,false,49.99,...,6.67,0.983768,-14.931816,0.67,11,0.00,0,0,0,True
945,34,False,0,1,492,True,D,True,false,48.81,...,1.33,0.594348,9.545471,4.00,16,0.00,0,0,0,False
947,34,False,0,2,13,True,B,True,false,59.85,...,2.00,1.035351,-2.681368,5.67,8,0.00,0,0,0,False
949,34,False,0,1,353,True,B,True,false,11.93,...,0.00,0.000000,-10.680936,0.00,12,0.00,0,0,0,False
953,34,False,0,1,226,False,C,True,false,36.24,...,1.00,1.274706,12.525650,1.67,7,0.33,0,0,0,True
955,34,False,0,2,15,True,B,True,false,50.24,...,4.00,0.522872,-14.802537,14.00,20,2.00,1,0,0,False
957,34,False,0,1,407,True,A,True,false,29.99,...,0.67,1.191465,-4.189863,0.33,14,0.00,0,0,0,True
968,34,False,0,1,231,True,G,True,false,42.66,...,27.33,0.698034,14.032992,12.33,8,0.00,0,0,2,False
970,34,False,0,2,23,True,E,True,false,53.98,...,2.33,1.134077,16.219673,15.33,29,0.67,0,0,0,False
971,34,False,0,1,322,True,B,True,false,20.81,...,0.00,5.330000,-2.803969,0.67,11,0.00,0,0,0,True
974,34,False,0,1,338,True,F,True,false,49.66,...,12.33,0.668515,-0.809136,7.67,12,0.00,0,0,0,True
982,34,False,0,2,193,True,C,True,false,108.70,...,0.00,3.801921,8.519612,0.67,12,0.33,0,0,0,True
987,34,False,0,1,231,True,B,True,false,85.07,...,3.67,2.381761,12.741383,4.33,8,0.00,0,0,2,False
988,34,False,0,3,199,True,B,True,false,30.27,...,2.67,2.226994,-13.396441,3.67,19,1.67,0,0,0,False
993,34,False,0,1,295,True,G,True,false,30.26,...,0.00,3.504505,20.065043,0.33,10,0.00,0,0,0,False
995,34,False,0,1,1040,False,A,True,false,32.69,...,2.33,2.724796,-6.108668,3.67,34,0.00,0,0,0,True
997,34,False,0,1,474,True,D,True,false,21.39,...,0.00,1.000000,-6.196988,0.67,16,0.33,0,0,0,False

In [185]:
#It is reasonable, they are "churn"
clean_data[(clean_data['avgBill']==0)]

,age,children,income,numHandsets,handsetAge,smartPhone,creditRating,homeOwner,creditCard,avgBill,...,avgInCalls,peakOffPeakRatio,peakOffPeakRatioChangePct,avgDroppedCalls,lifeTime,lastMonthCustomerCareCalls,numRetentionCalls,numRetentionOffersAccepted,newFrequentNumbers,churn
226,34,False,6,1,773,True,A,False,true,0.0,...,0.0,1.197605,13.684288,0.00,25,0.00,0,0,0,True
452,60,True,3,3,674,False,D,False,true,0.0,...,0.0,0.000000,-0.003758,0.00,34,0.00,0,0,0,True
481,34,False,0,2,323,True,F,True,false,0.0,...,0.0,2.572347,16.087536,4.67,29,0.33,0,0,0,True

In [186]:
#It is reasonable, they are "churn" or they avgInCalls is 0.
clean_data[(clean_data['avgMins']==0)]

,age,children,income,numHandsets,handsetAge,smartPhone,creditRating,homeOwner,creditCard,avgBill,...,avgInCalls,peakOffPeakRatio,peakOffPeakRatioChangePct,avgDroppedCalls,lifeTime,lastMonthCustomerCareCalls,numRetentionCalls,numRetentionOffersAccepted,newFrequentNumbers,churn
226,34,False,6,1,773,True,A,False,true,0.00,...,0.0,1.197605,13.684288,0.00,25,0.00,0,0,0,True
452,60,True,3,3,674,False,D,False,true,0.00,...,0.0,0.000000,-0.003758,0.00,34,0.00,0,0,0,True
481,34,False,0,2,323,True,F,True,false,0.00,...,0.0,2.572347,16.087536,4.67,29,0.33,0,0,0,True
619,56,True,8,1,774,True,B,False,true,42.49,...,0.0,0.000000,6.908503,0.33,26,0.33,0,0,0,True
635,34,False,0,1,579,True,B,True,false,5.00,...,0.0,0.000000,-17.709177,0.00,20,0.00,1,0,0,True
783,34,False,0,1,438,True,B,True,false,3.03,...,0.0,0.000000,-13.315054,0.00,14,0.00,0,0,0,False
844,38,False,7,1,530,True,B,False,true,35.16,...,0.0,0.000000,1.239732,0.00,17,0.00,0,0,0,True
870,34,False,0,2,463,True,C,True,false,5.00,...,0.0,0.000000,7.816691,0.00,31,0.00,0,0,0,True
902,34,False,7,3,562,True,C,False,true,5.00,...,0.0,0.000000,9.309546,0.00,37,0.00,0,0,0,True
904,32,False,8,2,1004,False,A,False,true,5.05,...,0.0,0.000000,8.787506,0.00,47,0.00,0,0,0,True
978,40,True,6,1,372,True,C,False,true,34.99,...,0.0,0.000000,4.987395,0.00,13,0.00,0,0,0,True

In [187]:
#It is reasonable, they are "churn"
clean_data[(clean_data['avgrecurringCharge']==0)]

,age,children,income,numHandsets,handsetAge,smartPhone,creditRating,homeOwner,creditCard,avgBill,...,avgInCalls,peakOffPeakRatio,peakOffPeakRatioChangePct,avgDroppedCalls,lifeTime,lastMonthCustomerCareCalls,numRetentionCalls,numRetentionOffersAccepted,newFrequentNumbers,churn
226,34,False,6,1,773,True,A,False,true,0.0,...,0.0,1.197605,13.684288,0.00,25,0.00,0,0,0,True
452,60,True,3,3,674,False,D,False,true,0.0,...,0.0,0.000000,-0.003758,0.00,34,0.00,0,0,0,True
481,34,False,0,2,323,True,F,True,false,0.0,...,0.0,2.572347,16.087536,4.67,29,0.33,0,0,0,True
870,34,False,0,2,463,True,C,True,false,5.0,...,0.0,0.000000,7.816691,0.00,31,0.00,0,0,0,True

In [188]:
#for numHandsets 
#It is seem that they may have many handsets. It is reasonable, so I keep it.
clean_data.sort_values(by='numHandsets', axis=0, ascending=False, inplace=False, kind='quicksort', na_position='last').head(7)

,age,children,income,numHandsets,handsetAge,smartPhone,creditRating,homeOwner,creditCard,avgBill,...,avgInCalls,peakOffPeakRatio,peakOffPeakRatioChangePct,avgDroppedCalls,lifeTime,lastMonthCustomerCareCalls,numRetentionCalls,numRetentionOffersAccepted,newFrequentNumbers,churn
258,50,False,5,13,162,True,E,True,true,60.19,...,39.00,2.631648,-29.612219,23.67,54,0.33,1,0,0,True
158,48,False,6,10,16,True,A,False,true,83.58,...,21.33,5.674000,-4.903635,17.33,54,0.00,0,0,0,False
919,28,False,1,9,58,True,B,True,true,79.49,...,30.33,1.018839,5.999242,36.00,34,0.33,0,0,0,True
367,48,True,9,8,15,True,C,False,true,59.81,...,19.00,1.025960,10.135476,4.33,25,0.00,0,0,0,False
567,58,False,3,8,237,True,E,False,true,102.61,...,20.67,2.359106,-14.326945,13.67,33,10.67,0,0,0,False
192,36,False,8,8,237,True,A,False,true,124.09,...,63.67,1.735632,2.942796,54.00,46,1.33,0,0,0,True
504,32,False,7,8,10,True,A,False,true,93.02,...,23.00,14.042685,-7.208502,14.67,56,0.00,0,0,0,False

In [189]:
#The handsetAge cannot be less than 0. So I decide to drop the rows with -2 and -1. 
#And for the value 0, it has "lifeTime=15", but they have 5 handsets, so maybe they just brought a new phone. So, it is poosible.
#And for vaule with 2, 3, they all have mutiple handsets, so they are possible.
clean_data.sort_values(by='handsetAge', axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last').head(5)

,age,children,income,numHandsets,handsetAge,smartPhone,creditRating,homeOwner,creditCard,avgBill,...,avgInCalls,peakOffPeakRatio,peakOffPeakRatioChangePct,avgDroppedCalls,lifeTime,lastMonthCustomerCareCalls,numRetentionCalls,numRetentionOffersAccepted,newFrequentNumbers,churn
168,32,False,1,2,-2,True,E,False,true,68.98,...,0.00,0.000000,9.379005,0.00,20,0.00,1,0,0,True
692,60,True,6,4,-1,True,F,False,true,88.98,...,0.00,0.000000,1.639013,0.00,40,0.00,0,0,0,False
115,20,False,1,5,0,True,E,True,false,149.98,...,14.00,0.576179,-7.789001,28.67,15,18.67,2,1,0,False
38,34,False,1,3,2,True,C,True,false,26.73,...,1.00,1.589744,-2.880754,11.00,12,4.67,0,0,1,True
669,26,False,9,2,3,True,B,False,true,83.66,...,49.67,2.000000,-3.682833,7.00,16,0.00,0,0,0,False

In [190]:
clean_data['handsetAge'].replace(-2, 2, inplace=True)
clean_data['handsetAge'].replace(-1, 1, inplace=True)

In [191]:
clean_data.sort_values(by='handsetAge', axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last').head(5)

,age,children,income,numHandsets,handsetAge,smartPhone,creditRating,homeOwner,creditCard,avgBill,...,avgInCalls,peakOffPeakRatio,peakOffPeakRatioChangePct,avgDroppedCalls,lifeTime,lastMonthCustomerCareCalls,numRetentionCalls,numRetentionOffersAccepted,newFrequentNumbers,churn
115,20,False,1,5,0,True,E,True,false,149.98,...,14.00,0.576179,-7.789001,28.67,15,18.67,2,1,0,False
692,60,True,6,4,1,True,F,False,true,88.98,...,0.00,0.000000,1.639013,0.00,40,0.00,0,0,0,False
168,32,False,1,2,2,True,E,False,true,68.98,...,0.00,0.000000,9.379005,0.00,20,0.00,1,0,0,True
38,34,False,1,3,2,True,C,True,false,26.73,...,1.00,1.589744,-2.880754,11.00,12,4.67,0,0,1,True
669,26,False,9,2,3,True,B,False,true,83.66,...,49.67,2.000000,-3.682833,7.00,16,0.00,0,0,0,False

In [192]:
#Altough the avgBill is huge, the avgMins is huge, so it is reasonable.
clean_data.sort_values(by='avgBill', axis=0, ascending=False, inplace=False, kind='quicksort', na_position='last').head(10).T

,670,407,9,495,140,468,599,91,638,532
age,36,50,22,50,52,46,26,30,34,54
children,False,True,False,False,False,False,False,False,False,False
income,1,7,4,1,8,9,7,3,0,7
numHandsets,2,4,1,3,3,1,2,2,2,2
handsetAge,303,88,337,269,83,320,127,62,89,145
smartPhone,True,True,True,True,True,True,True,True,True,True
creditRating,C,F,F,C,B,C,A,F,E,C
homeOwner,False,False,False,False,False,False,False,True,True,False
creditCard,true,true,true,true,false,true,true,false,false,true
avgBill,469.67,309.21,265.04,256.12,248.37,234.46,224.49,218.48,199.5,188.27
avgMins,4530.75,1825.25,1120,2726.75,2030,1556.5,2034.75,2786,1486.25,931.75
avgrecurringCharge,84.99,63.25,44.99,67.7,135.82,97.62,74.99,99.99,70,169.99
avgOverBundleMins,1389,641.5,649.5,451.25,194.25,237.25,353.25,436.33,505,0
avgRoamCalls,0,4.37,0,0,31.87,10.13,0,0,0,0
callMinutesChangePct,-19.355,-36.505,-3.48,8.285,-17.16,-3.21,-20.515,16.22,-6.305,2.405
billAmountChangePct,-3.9648,-0.6844,-0.625,-0.0366,-0.5518,-2.343,-2.8458,0.9612,-1.295,-0.5656
avgReceivedMins,1402.2,764.99,373.46,946.87,194.72,331.82,351.57,1026.59,704.17,266.93
avgOutCalls,91.33,217,27,105.33,34,64,43.33,64,67.67,18.67
avgInCalls,94.33,124.33,44,15.33,2,18.33,0,39.67,12,15
peakOffPeakRatio,0.824215,1.2442,4.29688,0.779773,1.26445,5.16842,1.64061,1.81806,1.59117,3.43111
peakOffPeakRatioChangePct,9.4103,3.00821,4.46643,-4.40966,-9.79427,-17.0385,10.2263,2.36785,2.22577,-3.16382
avgDroppedCalls,73,21,14,35,159.33,20.33,19.33,37,42.67,4
lifeTime,24,14,12,17,6,11,29,23,19,23
lastMonthCustomerCareCalls,5,5,0,10,4,1,1.33,9.33,4.67,1.33
numRetentionCalls,0,1,0,0,0,0,0,0,0,0
numRetentionOffersAccepted,0,0,0,0,0,0,0,0,0,0
newFrequentNumbers,0,0,0,3,0,0,0,0,1,0
churn,False,True,True,False,True,False,True,True,False,True

In [193]:
#They seem to be reasonable, for they pay more and have many incalls and outcalls, except the second value, they avgbill should be 449.6 but not 44.96
clean_data.sort_values(by='avgMins', axis=0, ascending=False, inplace=False, kind='quicksort', na_position='last').head(10).T

,670,887,285,374,149,704,338,91,495,661
age,36,50,34,54,34,38,34,30,50,34
children,False,False,False,True,False,True,False,False,False,False
income,1,4,4,5,0,3,6,3,1,0
numHandsets,2,7,5,1,7,1,5,2,3,4
handsetAge,303,489,185,304,28,207,139,62,269,11
smartPhone,True,True,True,True,True,True,True,True,True,True
creditRating,C,A,A,B,E,D,E,F,C,E
homeOwner,False,True,False,False,True,False,True,True,False,True
creditCard,true,true,true,true,false,true,false,false,true,false
avgBill,469.67,44.96,139.58,118.57,167.59,105.77,176.04,218.48,256.12,187.12
avgMins,4530.75,3584.25,3098.5,3066.75,2906.5,2872.75,2861.75,2786,2726.75,2639.75
avgrecurringCharge,84.99,58.79,75,59.99,159.99,50.07,94.99,99.99,67.7,159.99
avgOverBundleMins,1389,1094.25,248.75,167.5,9.75,133,232.25,436.33,451.25,116.5
avgRoamCalls,0,0,0,0.1,1.23,0,0,0,0,0
callMinutesChangePct,-19.355,-20.745,-0.71,8.805,9.63,6.505,-16.455,16.22,8.285,14.925
billAmountChangePct,-3.9648,2.4976,-0.4416,2.6878,-0.0686,-1.0156,-1.4234,0.9612,-0.0366,1.0138
avgReceivedMins,1402.2,732.57,1135.88,413.36,1353.14,598.05,899.48,1026.59,946.87,727.84
avgOutCalls,91.33,147.67,71.33,119,141.33,69.33,50,64,105.33,92
avgInCalls,94.33,55.33,65,27.67,283.67,18.67,52.33,39.67,15.33,3
peakOffPeakRatio,0.824215,5.13405,0.981755,0.402393,1.22625,0.493675,0.857296,1.81806,0.779773,3.32349
peakOffPeakRatioChangePct,9.4103,-0.77059,14.2764,2.05569,1.95429,-12.0626,-7.8618,2.36785,-4.40966,0.297966
avgDroppedCalls,73,119.67,48,24.33,24.33,39,171.67,37,35,2
lifeTime,24,51,42,11,17,7,10,23,17,22
lastMonthCustomerCareCalls,5,1.33,12.33,3.33,2,33,10,9.33,10,1
numRetentionCalls,0,0,0,0,0,1,0,0,0,0
numRetentionOffersAccepted,0,0,0,0,0,1,0,0,0,0
newFrequentNumbers,0,0,3,0,0,0,0,0,3,0
churn,False,True,False,False,False,False,False,True,False,False

In [194]:
# Reassign the avgBill for the person with high avgMin 3584.25.
clean_data.loc[887, 'avgBill']=449.6

In [195]:
#They avgBill and avgrecurringCharge are similar, so I think it is reasonable.
clean_data.sort_values(by='avgrecurringCharge', axis=0, ascending=False, inplace=False, kind='quicksort', na_position='last').head(10).T

,532,149,661,966,140,403,629,762,579,879
age,54,34,34,44,52,30,38,40,34,56
children,False,False,False,False,False,False,False,False,False,True
income,7,0,0,4,8,5,5,4,8,9
numHandsets,2,7,4,2,3,5,1,3,3,3
handsetAge,145,28,11,298,83,6,338,62,223,493
smartPhone,True,True,True,True,True,True,True,True,True,True
creditRating,C,E,E,A,B,D,B,E,C,A
homeOwner,False,True,True,False,False,False,False,True,False,False
creditCard,true,false,false,true,false,true,true,false,true,true
avgBill,188.27,167.59,187.12,165.18,248.37,106.47,107.24,184.47,115.25,117.16
avgMins,931.75,2906.5,2639.75,415.25,2030,1119,1353.75,1963.75,1679.5,810
avgrecurringCharge,169.99,159.99,159.99,159.99,135.82,119.99,119.99,119.07,110.4,109.98
avgOverBundleMins,0,9.75,116.5,8,194.25,0,11.25,195,45.75,6.75
avgRoamCalls,0,1.23,0,0,31.87,0,2.82,17.18,0,3.66
callMinutesChangePct,2.405,9.63,14.925,0.475,-17.16,-9.66,2.785,6.505,-6.27,2.26
billAmountChangePct,-0.5656,-0.0686,1.0138,-0.0388,-0.5518,-0.0296,0.051,-0.6286,-0.3052,-0.1298
avgReceivedMins,266.93,1353.14,727.84,48.4,194.72,370.49,297.75,390.91,378.78,205.65
avgOutCalls,18.67,141.33,92,16.67,34,33.67,106,150.67,46,26.33
avgInCalls,15,283.67,3,14.33,2,38.67,29.33,15,15,1.33
peakOffPeakRatio,3.43111,1.22625,3.32349,2.47222,1.26445,1.82383,6.40808,2.54306,1.03259,3.54015
peakOffPeakRatioChangePct,-3.16382,1.95429,0.297966,8.32158,-9.79427,-1.07659,2.58715,-1.72895,-10.5831,14.7164
avgDroppedCalls,4,24.33,2,6,159.33,11.33,13.67,27.67,24.67,11.33
lifeTime,23,17,22,46,6,7,12,16,10,37
lastMonthCustomerCareCalls,1.33,2,1,0.33,4,2.33,15.67,27.33,0.33,0
numRetentionCalls,0,0,0,0,0,0,0,0,0,0
numRetentionOffersAccepted,0,0,0,0,0,0,0,0,0,0
newFrequentNumbers,0,0,0,0,0,0,1,0,0,0
churn,True,False,False,False,True,True,False,True,False,True

In [196]:
#It is possible. And they pay more, so it is reasonable.
clean_data.sort_values(by='avgOverBundleMins', axis=0, ascending=False, inplace=False, kind='quicksort', na_position='last').head(10).T

,670,887,9,407,638,495,91,197,790,600
age,36,50,22,50,34,50,30,54,34,28
children,False,False,False,True,False,False,False,False,False,False
income,1,4,4,7,0,1,3,7,0,6
numHandsets,2,7,1,4,2,3,2,2,1,3
handsetAge,303,489,337,88,89,269,62,402,300,90
smartPhone,True,True,True,True,True,True,True,True,True,True
creditRating,C,A,F,F,E,C,F,A,G,B
homeOwner,False,True,False,False,True,False,True,False,True,False
creditCard,true,true,true,true,false,true,false,true,false,true
avgBill,469.67,449.6,265.04,309.21,199.5,256.12,218.48,181.82,172.69,187.64
avgMins,4530.75,3584.25,1120,1825.25,1486.25,2726.75,2786,575.25,1804.25,2425.75
avgrecurringCharge,84.99,58.79,44.99,63.25,70,67.7,99.99,29.99,54.99,101.85
avgOverBundleMins,1389,1094.25,649.5,641.5,505,451.25,436.33,421.75,367.75,363.25
avgRoamCalls,0,0,0,4.37,0,0,0,0,0,0
callMinutesChangePct,-19.355,-20.745,-3.48,-36.505,-6.305,8.285,16.22,-11.465,8.575,-12.215
billAmountChangePct,-3.9648,2.4976,-0.625,-0.6844,-1.295,-0.0366,0.9612,-3.0366,2.577,-0.6182
avgReceivedMins,1402.2,732.57,373.46,764.99,704.17,946.87,1026.59,151.55,349.5,667.27
avgOutCalls,91.33,147.67,27,217,67.67,105.33,64,41.33,128.33,199.67
avgInCalls,94.33,55.33,44,124.33,12,15.33,39.67,3,37,21.33
peakOffPeakRatio,0.824215,5.13405,4.29688,1.2442,1.59117,0.779773,1.81806,1.718,0.729204,1
peakOffPeakRatioChangePct,9.4103,-0.77059,4.46643,3.00821,2.22577,-4.40966,2.36785,-1.78813,-0.224713,16.111
avgDroppedCalls,73,119.67,14,21,42.67,35,37,16,26.67,16
lifeTime,24,51,12,14,19,17,23,25,10,14
lastMonthCustomerCareCalls,5,1.33,0,5,4.67,10,9.33,0,6,0
numRetentionCalls,0,0,0,1,0,0,0,0,0,0
numRetentionOffersAccepted,0,0,0,0,0,0,0,0,0,0
newFrequentNumbers,0,0,0,0,1,3,0,0,0,0
churn,False,True,True,True,False,False,True,True,False,False

In [197]:
#It is reasonable, they can make more avgRoamCalls. And they pay more for that.
clean_data.sort_values(by='avgRoamCalls', axis=0, ascending=False, inplace=False, kind='quicksort', na_position='last').head(10).T

,440,836,596,140,987,203,805,724,202,480
age,34,46,52,52,34,54,40,36,34,46
children,False,True,True,False,False,True,False,False,False,False
income,5,4,8,8,0,6,5,3,0,4
numHandsets,1,1,1,3,1,2,1,4,2,2
handsetAge,550,319,368,83,231,10,255,378,20,417
smartPhone,True,True,True,True,True,True,True,True,True,True
creditRating,C,G,B,B,B,A,B,A,C,B
homeOwner,True,False,False,False,True,False,False,False,True,False
creditCard,false,false,true,false,false,true,true,true,false,true
avgBill,116.91,187.84,92.42,248.37,85.07,59.97,65.64,149.39,109.64,81.64
avgMins,279,1369.5,1133.5,2030,452,227.25,264,1301.75,1513.25,137.25
avgrecurringCharge,50,59.71,59.99,135.82,62.99,29.99,49.99,75,94.99,57.49
avgOverBundleMins,0,211.75,9.75,194.25,4.75,17,1.25,0.75,6,0
avgRoamCalls,62.97,52.7,38.28,31.87,27.73,24.03,23.68,23.04,20.18,19.37
callMinutesChangePct,-5.56,-6.41,-3.63,-17.16,0.44,1.515,2.98,-4.915,-1.425,-2.745
billAmountChangePct,-1.2732,-0.9974,-0.7126,-0.5518,-0.1314,0.2858,-0.462,-0.7018,-0.4498,-0.418
avgReceivedMins,13.4,213.97,114.7,194.72,112.01,15.05,19.57,490.7,576.72,13.32
avgOutCalls,34.33,24.33,12.33,34,22,3.67,4.67,35.67,51.33,4.33
avgInCalls,2.67,0,1.67,2,3.67,0,1.67,2.67,9,0.67
peakOffPeakRatio,1.32172,2.16064,0.94792,1.26445,2.38176,13.3596,1,1.20946,0.436041,2.28022
peakOffPeakRatioChangePct,1.5518,9.26485,11.168,-9.79427,12.7414,0.8653,-7.57525,-0.32609,-12.7335,3.51657
avgDroppedCalls,8.67,35,10.67,159.33,4.33,2,3.33,6,97.33,8.67
lifeTime,18,11,13,6,8,34,9,50,7,17
lastMonthCustomerCareCalls,0,2,7.67,4,0,0,0,0,4,0
numRetentionCalls,0,0,0,0,0,0,0,0,0,0
numRetentionOffersAccepted,0,0,0,0,0,0,0,0,0,0
newFrequentNumbers,0,1,0,0,2,0,0,0,2,0
churn,True,True,True,True,False,False,False,True,True,True

In [198]:
#The first item seems to be not reasonable, for the number of customer care calls are too big. 
#The number of customer care calls of fourth item is greater than they avgoutcall, 
#   but they do have huge aveMins, and didn;t pay much. So, I think it is reasonable
clean_data.sort_values(by='lastMonthCustomerCareCalls', axis=0, ascending=False, inplace=False, kind='quicksort', na_position='last').head(5).T

                                 363      814      570       704       213
age                               40       30       52        38        34
children                       False    False    False      True     False
income                             4        5        6         3         0
numHandsets                        3        5        4         1         4
handsetAge                        35      118      480       207        70
smartPhone                      True     True     True      True      True
creditRating                       E        A        A         D         E
homeOwner                      False    False    False     False      True
creditCard                      true    false     true      true     false
avgBill                         35.1    50.58    75.48    105.77      66.7
avgMins                       1417.5      923  1502.25   2872.75   1253.75
avgrecurringCharge             44.99    59.99    94.99     50.07      77.7
avgOverBundleMins                  0      1.5        0       133         0
avgRoamCalls                       0        0        0         0         0
callMinutesChangePct            1.67     3.96   -6.405     6.505     3.225
billAmountChangePct           0.0064    0.035  -0.0098   -1.0156    0.2458
avgReceivedMins               234.33   157.79   194.98    598.05    275.41
avgOutCalls                   355.33    67.67    27.67     69.33     62.67
avgInCalls                     23.33     0.67     6.67     18.67     22.67
peakOffPeakRatio            0.264672  0.68395  1.41292  0.493675  0.919262
peakOffPeakRatioChangePct   -9.14683 -5.83117  3.95722  -12.0626  -11.0007
avgDroppedCalls                41.67       16    26.67        39     10.67
lifeTime                          25        7       46         7        13
lastMonthCustomerCareCalls    365.67    55.67       47        33     29.33
numRetentionCalls                  0        0        2         1         0
numRetentionOffersAccepted         0        0        1         1         0
newFrequentNumbers                 0        0        0         0         0
churn                          False     True    False     False     False

In [199]:
#change the number of customer care calls.
clean_data.loc[363, 'lastMonthCustomerCareCalls']=36.567

In [200]:
# It is possible. And they pay more, so it is reasonable
clean_data.sort_values(by='avgOutCalls', axis=0, ascending=False, inplace=False, kind='quicksort', na_position='last').head(3).T

                                 363      407      600
age                               40       50       28
children                       False     True    False
income                             4        7        6
numHandsets                        3        4        3
handsetAge                        35       88       90
smartPhone                      True     True     True
creditRating                       E        F        B
homeOwner                      False    False    False
creditCard                      true     true     true
avgBill                         35.1   309.21   187.64
avgMins                       1417.5  1825.25  2425.75
avgrecurringCharge             44.99    63.25   101.85
avgOverBundleMins                  0    641.5   363.25
avgRoamCalls                       0     4.37        0
callMinutesChangePct            1.67  -36.505  -12.215
billAmountChangePct           0.0064  -0.6844  -0.6182
avgReceivedMins               234.33   764.99   667.27
avgOutCalls                   355.33      217   199.67
avgInCalls                     23.33   124.33    21.33
peakOffPeakRatio            0.264672   1.2442        1
peakOffPeakRatioChangePct   -9.14683  3.00821   16.111
avgDroppedCalls                41.67       21       16
lifeTime                          25       14       14
lastMonthCustomerCareCalls    36.567        5        0
numRetentionCalls                  0        1        0
numRetentionOffersAccepted         0        0        0
newFrequentNumbers                 0        0        0
churn                          False     True    False

In [201]:
# It is possible. And they pay more, so it is reasonable
clean_data.sort_values(by='avgInCalls', axis=0, ascending=False, inplace=False, kind='quicksort', na_position='last').head(3).T

                                149       806      407
age                              34        28       50
children                      False     False     True
income                            0         4        7
numHandsets                       7         1        4
handsetAge                       28       200       88
smartPhone                     True      True     True
creditRating                      E         E        F
homeOwner                      True     False    False
creditCard                    false      true     true
avgBill                      167.59    182.85   309.21
avgMins                      2906.5   2534.25  1825.25
avgrecurringCharge           159.99    106.37    63.25
avgOverBundleMins              9.75       220    641.5
avgRoamCalls                   1.23         0     4.37
callMinutesChangePct           9.63    23.935  -36.505
billAmountChangePct         -0.0686    0.1116  -0.6844
avgReceivedMins             1353.14    931.48   764.99
avgOutCalls                  141.33     73.33      217
avgInCalls                   283.67       137   124.33
peakOffPeakRatio            1.22625  0.884019   1.2442
peakOffPeakRatioChangePct   1.95429   37.7797  3.00821
avgDroppedCalls               24.33     53.33       21
lifeTime                         17         7       14
lastMonthCustomerCareCalls        2         4        5
numRetentionCalls                 0         0        1
numRetentionOffersAccepted        0         0        0
newFrequentNumbers                0         2        0
churn                         False     False     True

In [202]:
clean_data.to_csv('ready2.csv', index=False)

In [203]:
ready_data = pd.read_csv('ready2.csv')

In [204]:
print("done1")

done1